export const content = {
  et: {
    nav: {
      about: 'Meist',
      stay: 'Majutus',
      amenities: 'Tegevused',
      pricing: 'Hinnakiri',
      gallery: 'Galerii',
      contact: 'Kontakt',
    },
    hero: {
      eyebrow: 'Peipsi järve kaldal',
      title: 'Willipu külalisemaja ja karavanipark',
      subtitle:
        'Vaikne paik vee ääres — kohtumiseks, puhkuseks ja peoks. Tartumaal, Pusi külas.',
      cta: 'Broneeri ööbimine karavanipargis',
      ctaAlt: 'Vaata hindu',
      ctaNote: 'Tubade ja kämpingute broneerimine emaili teel.',
    },
    about: {
      kicker: 'Tere tulemast',
      title: 'Üle 20 aasta kogemusi',
      body:
        'Willipu asub Tartumaal, Alatskivi vallas, Pusi külas, otse Peipsi järve kaldal. Lähim linn Kallaste jääb 2 km kaugusele, Tartu 50 km ja Tallinn 200 km kaugusele. Pakume majutust nii peamajas kui ka suvemajakestes, ruumi pidudeks ja koolitusteks ning kohta haagissuvilatele.',
      stats: [
        { value: '10', label: 'kohta peamajas' },
        { value: '30', label: 'kohta peosaalis' },
        { value: '41', label: 'haagissuvila kohta' },
        { value: '2 km', label: 'Kallaste linna' },
        { value: '16', label: 'kohta kämpingutes' },
        { value: 'kuni 5', label: 'lisakohta' },
        { value: '🏖', label: 'lapsesõbralik liivarand' },
        { value: '🌿', label: 'suur muruplats väliürituste korraldamiseks' },
      ],
    },
    stay: {
      kicker: 'Majutus',
      title: 'Vali endale sobiv variant',
      cards: [
        {
          name: 'Peamaja',
          tagline: '2–3 inimese toad, kuni 10 külalist',
          desc:
            'Kolmes toas on TV, WiFi, dušš ja WC. Ühel toal on dušš ja WC koridoris. Esimesel korrusel asub peosaal kuni 30 inimesele.',
          price: 'al. 25 € / inimene',
        },
        {
          name: 'Pereaiamaja',
          tagline: '5 magamiskohta, köök, dušš, WC',
          desc:
            'Kaks tuba, WC, dušš ja köök. Konditsioneer. Sobib perele või väiksele seltskonnale.',
          price: '110 € / öö',
        },
        {
          name: 'Väike aiamaja',
          tagline: '2 magamiskohta, soojustatud',
          desc:
            'Talvel kasutatav, sooja vee ja WC-ga. Mõnus paaridele või paigaks, kui peamaja täis.',
          price: '40 € / öö',
        },
        {
          name: 'Karavani park',
          tagline: 'Elekter, vesi, duššid, WC',
          desc:
            'Kuni 41 haagissuvilakohta. Elektri-, vee- ja kanalisatsiooniühendused. Telkimine lubatud.',
          price: 'al. 14 € / öö',
        },
      ],
    },
    amenities: {
      kicker: 'Mida teha',
      title: 'Tegevused vee ääres',
      items: [
        { icon: 'wave', title: 'Ujumine ja surf', body: 'Liivane rand, sobib ka surfaritele.' },
        { icon: 'ball', title: 'Võrkpall ja mängud', body: 'Õueplatsid ja vabad muruväljakud.' },
        { icon: 'fire', title: 'Lõke ja saun', body: 'Lõkkeplats ning saun seltskonnale.' },
        { icon: 'hall', title: 'Peosaal kuni 30', body: 'Konverentsid, peod, koolitused.' },
        { icon: 'wifi', title: 'Kiire WiFi kogu territooriumil', body: 'Tasuta kiire WiFi kogu territooriumil.' },
      ],
    },
    pricing: {
      kicker: 'Hinnakiri',
      title: 'Soodsad hinnad, kõigi mugavustega',
      note:
        'Broneeringu kinnitamiseks tasutakse 50% ettemaksuna. Tühistamisel alla 14 päeva ettemaks ei tagastata.',
      downloadLabel: 'Laadi hinnakiri alla (.xlsx)',
      groups: [
        {
          label: 'Suur kämpingumaja',
          icon: '🏡',
          photos: [
            { url: '/suur_kamp1.jpg', alt: 'Suur kämpingumaja' },
            { url: '/suur_kamp2.jpg', alt: 'Suur kämpingumaja' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Dušš' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Köök' },
            { icon: 'grill', label: 'Grill' },
          ],
          rows: [
            { item: '5 inimesele', price: '110 € / öö' },
            { item: '4 inimesele', price: '100 € / öö' },
            { item: '2–3 inimesele', price: '85 € / öö' },
          ],
        },
        {
          label: 'Väike kämpingumaja',
          icon: '🛖',
          photos: [
            { url: '/v4.jpeg', alt: 'Väike kämpingumaja' },
            { url: '/v1.jpeg', alt: 'Väike kämpingumaja' },
            { url: '/v2.jpeg', alt: 'Väike kämpingumaja' },
            { url: '/v3.jpeg', alt: 'Väike kämpingumaja' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'grill', label: 'Grill' },
          ],
          rows: [
            { item: '2 inimesele', price: '55 € / öö' },
            { item: '1 inimesele', price: '35 € / öö' },
          ],
        },
        {
          label: 'Peamaja - kahene tuba',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Peamaja' },
            { url: '/peamaja%201.jpg', alt: 'Peamaja' },
            { url: '/peamaja%202.jpg', alt: 'Peamaja' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Köök' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Köök' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Dušš' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Ühine köök' },
            { icon: 'grill', label: 'Grill' },
          ],
          rows: [
            { item: '2 inimesele', price: '55 € / öö' },
            { item: '1 inimesele', price: '35 € / öö' },
          ],
        },
        {
          label: 'Peamaja - kolmene tuba',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Peamaja' },
            { url: '/peamaja%201.jpg', alt: 'Peamaja' },
            { url: '/peamaja%202.jpg', alt: 'Peamaja' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Köök' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Köök' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Dušš' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Ühine köök' },
            { icon: 'grill', label: 'Grill' },
          ],
          rows: [
            { item: '3 inimesele', price: '80 € / öö' },
            { item: '2 inimesele', price: '60 € / öö' },
          ],
        },
        {
          label: 'Karavanipark 24/7',
          icon: '🚐',
          photos: [
            { url: '/kar1.jpg', alt: 'Karavanipark' },
            { url: '/kar2.jpg', alt: 'Karavanipark' },
            { url: '/kar3.jpg', alt: 'Karavanipark' },
            { url: '/kar4.jpg', alt: 'Karavanipark' },
          ],
          amenities: [
            { icon: 'checkin', label: 'Check-in 24/7', tooltip: 'Iseteeninduslik check-in' },
            { icon: 'electric', label: 'Elekter' },
            { icon: 'shower', label: 'Dušš' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'water', label: 'Puhas vesi' },
            { icon: 'dump', label: 'Purgimine' },
            { icon: 'chemical', label: 'Keemiline WC' },
            { icon: 'kitchen', label: 'Köök' },
            { icon: 'washer', label: 'Pesumasin' },
            { icon: 'trash', label: 'Prügi äraandmine' },
            { icon: 'pets', label: 'Lemmikloomad lubatud' },
          ],
          rows: [
            { item: 'Haagissuvila ilma elektrita', price: '20 € / öö', note: 'sisaldab 2 inimest' },
            { item: 'Haagissuvila elektriga', price: '25 € / öö', note: 'sisaldab 2 inimest' },
            { item: 'Haagissuvila lisa inimene', price: '3 € / inimene' },
            { item: 'Telkimine', price: '7 € / inimene' },
          ],
        },
        {
          label: 'Muud',
          icon: '❄️',
          rows: [
            { item: 'Talvine järvetransport', price: 'küsi hinda' },
          ],
        },
      ],
    },
    contact: {
      kicker: 'Kontakt',
      title: 'Tule külla või võta ühendust',
      address: 'Pusi küla, Alatskivi vald, Tartumaa',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=58.64483549867105,27.166508285762042',
      locationLabel: 'Asukoht',
      hoursLabel: 'Lahtiolekuajad',
      hours: 'Avatud aastaringselt',
      phone: '+372 56 955 758',
      email: 'willipu.willipu@gmail.com',
      cta: 'Saada e-kiri',
      legal: {
        companyName: 'OÜ Willipu Turism',
        reg: '10972974',
        vat: 'EE100878462',
        legalAddress: 'Villipu, Pusi küla, 60217 Peipsiääre vald, Tartu maakond',
      },
    },
    floatContact: {
      tab: 'Kirjuta meile',
      title: 'Kirjuta meile',
      namePlaceholder: 'Sinu nimi',
      emailPlaceholder: 'Sinu e-post',
      messagePlaceholder: 'Sinu sõnum...',
      send: 'Ava e-postirakendus',
      hint: 'Vajutades avab sinu e-postirakenduse eeltäidetud kirjaga.',
      emailSubject: 'Päring Willipu kodulehelt — {name}',
      emailFrom: 'Nimi',
      emailReply: 'Vastuse aadress',
    },
    footer: {
      tagline: 'Peipsi järve ääres alates 2010.',
      rights: 'Kõik õigused kaitstud',
    },
  },
  en: {
    nav: {
      about: 'About',
      stay: 'Stay',
      amenities: 'Activities',
      pricing: 'Pricing',
      gallery: 'Gallery',
      contact: 'Contact',
    },
    hero: {
      eyebrow: 'On the shore of Lake Peipus',
      title: 'Willipu Guesthouse and Caravan Park',
      subtitle:
        'A quiet place by the water — for gatherings, getaways and good food. In Pusi village, southern Estonia.',
      cta: 'Book a stay at the caravan park',
      ctaAlt: 'See pricing',
      ctaNote: 'Room and cottage bookings by email.',
    },
    about: {
      kicker: 'Welcome',
      title: 'Over 20 years of experience',
      body:
        'Willipu sits in Tartu county, Alatskivi commune, Pusi village — right on the shore of Lake Peipus. The nearest town Kallaste is 2 km away, Tartu is 50 km, Tallinn 200 km. We offer rooms in the main house, summer cottages, a banquet hall for events and a full caravan park.',
      stats: [
        { value: '10', label: 'beds in main house' },
        { value: '30', label: 'seats in banquet hall' },
        { value: '41', label: 'caravan spots' },
        { value: '2 km', label: 'to Kallaste' },
        { value: '16', label: 'beds in cottages' },
        { value: 'up to 5', label: 'extra beds' },
        { value: '🏖', label: 'child-friendly sandy beach' },
        { value: '🌿', label: 'large lawn for outdoor events' },
      ],
    },
    stay: {
      kicker: 'Stay',
      title: 'Find the right place to sleep',
      cards: [
        {
          name: 'Main house',
          tagline: 'Rooms for 2–3, up to 10 guests',
          desc:
            'Three rooms have TV, WiFi, shower and toilet. One room has shower and toilet in the hall. The ground floor holds our banquet hall for up to 30 people.',
          price: 'from €25 / person',
        },
        {
          name: 'Family cottage',
          tagline: '5 beds, kitchen, shower, toilet',
          desc:
            'Two bedrooms, full bathroom and kitchen. Air conditioning. Comfortable for a family or small group.',
          price: '€110 / night',
        },
        {
          name: 'Small cottage',
          tagline: '2 beds, heated, year-round',
          desc:
            'Insulated for winter use, with hot water and toilet. A cosy spot for couples or overflow guests.',
          price: '€40 / night',
        },
        {
          name: 'Caravan park',
          tagline: 'Power, water, showers, WC',
          desc:
            'Up to 41 caravan spots with electric, water and sewage hookups. Tent camping welcome.',
          price: 'from €14 / night',
        },
      ],
    },
    amenities: {
      kicker: 'Things to do',
      title: 'Life by the lake',
      items: [
        { icon: 'wave', title: 'Swim and surf', body: 'Sandy beach, also great for windsurfers.' },
        { icon: 'ball', title: 'Volleyball and games', body: 'Outdoor courts and open lawns.' },
        { icon: 'fire', title: 'Bonfire and sauna', body: 'Fire pit and sauna for groups.' },
        { icon: 'hall', title: 'Banquet hall for 30', body: 'Conferences, parties, trainings.' },
        { icon: 'wifi', title: 'Fast WiFi across the property', body: 'Free high-speed WiFi across the entire property.' },
      ],
    },
    pricing: {
      kicker: 'Pricing',
      title: 'Affordable prices, all comforts included',
      note:
        'A 50% deposit confirms your booking. Cancellations within 14 days of arrival forfeit the deposit.',
      downloadLabel: 'Download price list (.xlsx)',
      groups: [
        {
          label: 'Large Camping Cottage',
          icon: '🏡',
          photos: [
            { url: '/suur_kamp1.jpg', alt: 'Large Camping Cottage' },
            { url: '/suur_kamp2.jpg', alt: 'Large Camping Cottage' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Shower' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Kitchen' },
            { icon: 'grill', label: 'BBQ' },
          ],
          rows: [
            { item: '5 persons', price: '€110 / night' },
            { item: '4 persons', price: '€100 / night' },
            { item: '2–3 persons', price: '€85 / night' },
          ],
        },
        {
          label: 'Small Camping Cottage',
          icon: '🛖',
          photos: [
            { url: '/v4.jpeg', alt: 'Small Camping Cottage' },
            { url: '/v1.jpeg', alt: 'Small Camping Cottage' },
            { url: '/v2.jpeg', alt: 'Small Camping Cottage' },
            { url: '/v3.jpeg', alt: 'Small Camping Cottage' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'grill', label: 'BBQ' },
          ],
          rows: [
            { item: '2 persons', price: '€55 / night' },
            { item: '1 person', price: '€35 / night' },
          ],
        },
        {
          label: 'Main house - double room',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Main house' },
            { url: '/peamaja%201.jpg', alt: 'Main house' },
            { url: '/peamaja%202.jpg', alt: 'Main house' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Kitchen' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Kitchen' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Shower' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Shared kitchen' },
            { icon: 'grill', label: 'BBQ' },
          ],
          rows: [
            { item: '2 persons', price: '€55 / night' },
            { item: '1 person', price: '€35 / night' },
          ],
        },
        {
          label: 'Main house - triple room',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Main house' },
            { url: '/peamaja%201.jpg', alt: 'Main house' },
            { url: '/peamaja%202.jpg', alt: 'Main house' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Kitchen' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Kitchen' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Shower' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Shared kitchen' },
            { icon: 'grill', label: 'BBQ' },
          ],
          rows: [
            { item: '3 persons', price: '€80 / night' },
            { item: '2 persons', price: '€60 / night' },
          ],
        },
        {
          label: 'Caravan Park 24/7',
          icon: '🚐',
          photos: [
            { url: '/kar1.jpg', alt: 'Caravan Park' },
            { url: '/kar2.jpg', alt: 'Caravan Park' },
            { url: '/kar3.jpg', alt: 'Caravan Park' },
            { url: '/kar4.jpg', alt: 'Caravan Park' },
          ],
          amenities: [
            { icon: 'checkin', label: 'Check-in 24/7', tooltip: 'Self-service check-in' },
            { icon: 'electric', label: 'Electric' },
            { icon: 'shower', label: 'Shower' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'water', label: 'Fresh water' },
            { icon: 'dump', label: 'Waste dump' },
            { icon: 'chemical', label: 'Chemical WC' },
            { icon: 'kitchen', label: 'Kitchen' },
            { icon: 'washer', label: 'Washer' },
            { icon: 'trash', label: 'Waste disposal' },
            { icon: 'pets', label: 'Pets welcome' },
          ],
          rows: [
            { item: 'Caravan without power', price: '€20 / night', note: 'includes 2 persons' },
            { item: 'Caravan with power', price: '€25 / night', note: 'includes 2 persons' },
            { item: 'Caravan extra person', price: '€3 / person' },
            { item: 'Tent camping', price: '€7 / person' },
          ],
        },
        {
          label: 'Other',
          icon: '❄️',
          rows: [
            { item: 'Winter lake transport', price: 'ask for price' },
          ],
        },
      ],
    },
    contact: {
      kicker: 'Contact',
      title: 'Come visit or get in touch',
      address: 'Pusi village, Alatskivi parish, Tartu county',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=58.64483549867105,27.166508285762042',
      locationLabel: 'Location',
      hoursLabel: 'Opening hours',
      hours: 'Open year-round',
      phone: '+372 56 955 758',
      email: 'willipu.willipu@gmail.com',
      cta: 'Send an email',
      legal: {
        companyName: 'OÜ Willipu Turism',
        reg: '10972974',
        vat: 'EE100878462',
        legalAddress: 'Villipu, Pusi küla, 60217 Peipsiääre vald, Tartu maakond',
      },
    },
    floatContact: {
      tab: 'Contact us',
      title: 'Send us a message',
      namePlaceholder: 'Your name',
      emailPlaceholder: 'Your email',
      messagePlaceholder: 'Your message...',
      send: 'Open email app',
      hint: 'Clicking will open your email app with a pre-filled message.',
      emailSubject: 'Enquiry from willipu.ee — {name}',
      emailFrom: 'Name',
      emailReply: 'Reply to',
    },
    footer: {
      tagline: 'On Lake Peipus since 2010.',
      rights: 'All rights reserved',
    },
  },
  de: {
    nav: {
      about: 'Über uns',
      stay: 'Unterkunft',
      amenities: 'Aktivitäten',
      pricing: 'Preise',
      gallery: 'Galerie',
      contact: 'Kontakt',
    },
    hero: {
      eyebrow: 'Am Ufer des Peipussees',
      title: 'Willipu Gästehaus und Campingpark',
      subtitle: 'Ein ruhiger Ort am Wasser — zum Treffen, Erholen und Feiern. Im Dorf Pusi, Südestland.',
      cta: 'Stellplatz im Campingpark buchen',
      ctaAlt: 'Preise ansehen',
      ctaNote: 'Zimmer- und Hüttenbuchungen per E-Mail.',
    },
    about: {
      kicker: 'Willkommen',
      title: 'Über 20 Jahre Erfahrung',
      body: 'Willipu liegt im Kreis Tartu, Gemeinde Alatskivi, Dorf Pusi — direkt am Ufer des Peipussees. Die nächste Stadt Kallaste ist 2 km entfernt, Tartu 50 km und Tallinn 200 km. Wir bieten Zimmer im Haupthaus, Sommerhütten, einen Festsaal für Veranstaltungen und einen vollständigen Campingpark.',
      stats: [
        { value: '10', label: 'Betten im Haupthaus' },
        { value: '30', label: 'Plätze im Festsaal' },
        { value: '41', label: 'Campingstellplätze' },
        { value: '2 km', label: 'bis Kallaste' },
        { value: '16', label: 'Betten in Hütten' },
        { value: 'bis 5', label: 'Zusatzbetten' },
        { value: '🏖', label: 'kinderfreundlicher Sandstrand' },
        { value: '🌿', label: 'großer Rasen für Freiluftveranstaltungen' },
      ],
    },
    amenities: {
      kicker: 'Aktivitäten',
      title: 'Freizeitangebote am See',
      items: [
        { icon: 'wave', title: 'Schwimmen und Surfen', body: 'Sandstrand, ideal auch für Windsurfer.' },
        { icon: 'ball', title: 'Volleyball und Spiele', body: 'Außenplätze und offene Rasenflächen.' },
        { icon: 'fire', title: 'Lagerfeuer und Sauna', body: 'Feuerstelle und Sauna für Gruppen.' },
        { icon: 'hall', title: 'Festsaal für 30', body: 'Konferenzen, Feiern, Schulungen.' },
        { icon: 'wifi', title: 'Schnelles WLAN auf dem gesamten Gelände', body: 'Kostenloses Hochgeschwindigkeits-WLAN auf dem gesamten Gelände.' },
      ],
    },
    pricing: {
      kicker: 'Preise',
      title: 'Günstige Preise, alle Annehmlichkeiten inklusive',
      note: 'Eine Anzahlung von 50 % bestätigt Ihre Buchung. Bei Stornierung innerhalb von 14 Tagen vor Anreise verfällt die Anzahlung.',
      downloadLabel: 'Preisliste herunterladen (.xlsx)',
      groups: [
        {
          label: 'Großes Campinghaus',
          icon: '🏡',
          photos: [
            { url: '/suur_kamp1.jpg', alt: 'Großes Campinghaus' },
            { url: '/suur_kamp2.jpg', alt: 'Großes Campinghaus' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Dusche' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Küche' },
            { icon: 'grill', label: 'Grill' },
          ],
          rows: [
            { item: '5 Personen', price: '110 € / Nacht' },
            { item: '4 Personen', price: '100 € / Nacht' },
            { item: '2–3 Personen', price: '85 € / Nacht' },
          ],
        },
        {
          label: 'Kleines Campinghaus',
          icon: '🛖',
          photos: [
            { url: '/v4.jpeg', alt: 'Kleines Campinghaus' },
            { url: '/v1.jpeg', alt: 'Kleines Campinghaus' },
            { url: '/v2.jpeg', alt: 'Kleines Campinghaus' },
            { url: '/v3.jpeg', alt: 'Kleines Campinghaus' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'grill', label: 'Grill' },
          ],
          rows: [
            { item: '2 Personen', price: '55 € / Nacht' },
            { item: '1 Person', price: '35 € / Nacht' },
          ],
        },
        {
          label: 'Haupthaus - Doppelzimmer',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Haupthaus' },
            { url: '/peamaja%201.jpg', alt: 'Haupthaus' },
            { url: '/peamaja%202.jpg', alt: 'Haupthaus' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Küche' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Küche' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Dusche' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Gemeinschaftsküche' },
            { icon: 'grill', label: 'Grill' },
          ],
          rows: [
            { item: '2 Personen', price: '55 € / Nacht' },
            { item: '1 Person', price: '35 € / Nacht' },
          ],
        },
        {
          label: 'Haupthaus - Dreibettzimmer',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Haupthaus' },
            { url: '/peamaja%201.jpg', alt: 'Haupthaus' },
            { url: '/peamaja%202.jpg', alt: 'Haupthaus' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Küche' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Küche' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Dusche' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Gemeinschaftsküche' },
            { icon: 'grill', label: 'Grill' },
          ],
          rows: [
            { item: '3 Personen', price: '80 € / Nacht' },
            { item: '2 Personen', price: '60 € / Nacht' },
          ],
        },
        {
          label: 'Campingpark 24/7',
          icon: '🚐',
          photos: [
            { url: '/kar1.jpg', alt: 'Campingpark' },
            { url: '/kar2.jpg', alt: 'Campingpark' },
            { url: '/kar3.jpg', alt: 'Campingpark' },
            { url: '/kar4.jpg', alt: 'Campingpark' },
          ],
          amenities: [
            { icon: 'checkin', label: 'Check-in 24/7', tooltip: 'Selbstbedienung Check-in' },
            { icon: 'electric', label: 'Strom' },
            { icon: 'shower', label: 'Dusche' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'water', label: 'Frischwasser' },
            { icon: 'dump', label: 'Abwasserentsorgung' },
            { icon: 'chemical', label: 'Chemie-WC' },
            { icon: 'kitchen', label: 'Küche' },
            { icon: 'washer', label: 'Waschmaschine' },
            { icon: 'trash', label: 'Müllentsorgung' },
            { icon: 'pets', label: 'Haustiere erlaubt' },
          ],
          rows: [
            { item: 'Wohnwagen ohne Strom', price: '20 € / Nacht', note: 'inkl. 2 Personen' },
            { item: 'Wohnwagen mit Strom', price: '25 € / Nacht', note: 'inkl. 2 Personen' },
            { item: 'Wohnwagen Zusatzperson', price: '3 € / Person' },
            { item: 'Zelten', price: '7 € / Person' },
          ],
        },
        {
          label: 'Sonstiges',
          icon: '❄️',
          rows: [
            { item: 'Winter-Seetransport', price: 'Preis auf Anfrage' },
          ],
        },
      ],
    },
    contact: {
      kicker: 'Kontakt',
      title: 'Besuchen Sie uns oder nehmen Sie Kontakt auf',
      address: 'Dorf Pusi, Gemeinde Alatskivi, Kreis Tartu',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=58.64483549867105,27.166508285762042',
      locationLabel: 'Standort',
      hoursLabel: 'Öffnungszeiten',
      hours: 'Ganzjährig geöffnet',
      phone: '+372 56 955 758',
      email: 'willipu.willipu@gmail.com',
      cta: 'E-Mail senden',
      legal: {
        companyName: 'OÜ Willipu Turism',
        reg: '10972974',
        vat: 'EE100878462',
        legalAddress: 'Villipu, Pusi küla, 60217 Peipsiääre vald, Tartu maakond',
      },
    },
    floatContact: {
      tab: 'Schreib uns',
      title: 'Nachricht senden',
      namePlaceholder: 'Ihr Name',
      emailPlaceholder: 'Ihre E-Mail',
      messagePlaceholder: 'Ihre Nachricht...',
      send: 'E-Mail-App öffnen',
      hint: 'Klicken öffnet Ihr E-Mail-Programm mit einer vorausgefüllten Nachricht.',
      emailSubject: 'Anfrage von willipu.ee — {name}',
      emailFrom: 'Name',
      emailReply: 'Antwort an',
    },
    footer: {
      tagline: 'Am Peipussee seit 2010.',
      rights: 'Alle Rechte vorbehalten',
    },
  },
  fi: {
    nav: {
      about: 'Meistä',
      stay: 'Majoitus',
      amenities: 'Aktiviteetit',
      pricing: 'Hinnat',
      gallery: 'Galleria',
      contact: 'Yhteystiedot',
    },
    hero: {
      eyebrow: 'Peipsijärven rannalla',
      title: 'Willipu vierastalo ja asuntovaunupuisto',
      subtitle: 'Rauhallinen paikka veden äärellä — kokoontumisiin, lomailuun ja juhliin. Pusin kylässä, Etelä-Virossa.',
      cta: 'Varaa paikka asuntovaunupuistosta',
      ctaAlt: 'Katso hinnat',
      ctaNote: 'Huoneiden ja mökkien varaukset sähköpostitse.',
    },
    about: {
      kicker: 'Tervetuloa',
      title: 'Yli 20 vuoden kokemus',
      body: 'Willipu sijaitsee Tarton maakunnassa, Alatskivin kunnassa, Pusin kylässä – suoraan Peipsijärven rannalla. Lähin kaupunki Kallaste on 2 km päässä, Tartu 50 km ja Tallinn 200 km. Tarjoamme huoneita päätalossa, kesämökkejä, juhlatilan tapahtumia varten sekä täyden asuntovaunualueen.',
      stats: [
        { value: '10', label: 'paikkaa päätalossa' },
        { value: '30', label: 'paikkaa juhlatilassa' },
        { value: '41', label: 'asuntovaunupaikkaa' },
        { value: '2 km', label: 'Kallasteen kaupunkiin' },
        { value: '16', label: 'paikkaa mökeissä' },
        { value: 'enint. 5', label: 'lisäpaikkaa' },
        { value: '🏖', label: 'lapsiystävällinen hiekkaranta' },
        { value: '🌿', label: 'suuri nurmialue ulkotapahtumia varten' },
      ],
    },
    amenities: {
      kicker: 'Aktiviteetit',
      title: 'Tekemistä järven rannalla',
      items: [
        { icon: 'wave', title: 'Uinti ja surffaus', body: 'Hiekkaranta, sopii myös purjelautailijoille.' },
        { icon: 'ball', title: 'Lentopallo ja pelit', body: 'Ulkokentät ja avoimet nurmikenttät.' },
        { icon: 'fire', title: 'Nuotio ja sauna', body: 'Nuotiopaikka ja sauna ryhmille.' },
        { icon: 'hall', title: 'Juhlatila 30 hengelle', body: 'Kokoukset, juhlat, koulutukset.' },
        { icon: 'wifi', title: 'Nopea WiFi koko alueella', body: 'Ilmainen nopea WiFi koko alueella.' },
      ],
    },
    pricing: {
      kicker: 'Hinnat',
      title: 'Edulliset hinnat, kaikki mukavuudet mukana',
      note: '50 %:n ennakkomaksu vahvistaa varauksen. Peruutuksista alle 14 päivää ennen saapumista ennakkomaksua ei palauteta.',
      downloadLabel: 'Lataa hinnasto (.xlsx)',
      groups: [
        {
          label: 'Suuri leirintämökki',
          icon: '🏡',
          photos: [
            { url: '/suur_kamp1.jpg', alt: 'Suuri leirintämökki' },
            { url: '/suur_kamp2.jpg', alt: 'Suuri leirintämökki' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Suihku' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Keittiö' },
            { icon: 'grill', label: 'Grilli' },
          ],
          rows: [
            { item: '5 henkilöä', price: '110 € / yö' },
            { item: '4 henkilöä', price: '100 € / yö' },
            { item: '2–3 henkilöä', price: '85 € / yö' },
          ],
        },
        {
          label: 'Pieni leirintämökki',
          icon: '🛖',
          photos: [
            { url: '/v4.jpeg', alt: 'Pieni leirintämökki' },
            { url: '/v1.jpeg', alt: 'Pieni leirintämökki' },
            { url: '/v2.jpeg', alt: 'Pieni leirintämökki' },
            { url: '/v3.jpeg', alt: 'Pieni leirintämökki' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'grill', label: 'Grilli' },
          ],
          rows: [
            { item: '2 henkilöä', price: '55 € / yö' },
            { item: '1 henkilö', price: '35 € / yö' },
          ],
        },
        {
          label: 'Päätalo - kahden hengen huone',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Päätalo' },
            { url: '/peamaja%201.jpg', alt: 'Päätalo' },
            { url: '/peamaja%202.jpg', alt: 'Päätalo' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Keittiö' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Keittiö' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Suihku' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Yhteiskeittiö' },
            { icon: 'grill', label: 'Grilli' },
          ],
          rows: [
            { item: '2 henkilöä', price: '55 € / yö' },
            { item: '1 henkilö', price: '35 € / yö' },
          ],
        },
        {
          label: 'Päätalo - kolmen hengen huone',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Päätalo' },
            { url: '/peamaja%201.jpg', alt: 'Päätalo' },
            { url: '/peamaja%202.jpg', alt: 'Päätalo' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Keittiö' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Keittiö' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Suihku' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Yhteiskeittiö' },
            { icon: 'grill', label: 'Grilli' },
          ],
          rows: [
            { item: '3 henkilöä', price: '80 € / yö' },
            { item: '2 henkilöä', price: '60 € / yö' },
          ],
        },
        {
          label: 'Asuntovaunupuisto 24/7',
          icon: '🚐',
          photos: [
            { url: '/kar1.jpg', alt: 'Asuntovaunupuisto' },
            { url: '/kar2.jpg', alt: 'Asuntovaunupuisto' },
            { url: '/kar3.jpg', alt: 'Asuntovaunupuisto' },
            { url: '/kar4.jpg', alt: 'Asuntovaunupuisto' },
          ],
          amenities: [
            { icon: 'checkin', label: 'Check-in 24/7', tooltip: 'Itsepalvelu check-in' },
            { icon: 'electric', label: 'Sähkö' },
            { icon: 'shower', label: 'Suihku' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'water', label: 'Puhdas vesi' },
            { icon: 'dump', label: 'Jäteveden tyhjennys' },
            { icon: 'chemical', label: 'Kemiallinen WC' },
            { icon: 'kitchen', label: 'Keittiö' },
            { icon: 'washer', label: 'Pesukone' },
            { icon: 'trash', label: 'Jätteiden käsittely' },
            { icon: 'pets', label: 'Lemmikit sallittu' },
          ],
          rows: [
            { item: 'Asuntovaunu ilman sähköä', price: '20 € / yö', note: 'sis. 2 henkilöä' },
            { item: 'Asuntovaunu sähköllä', price: '25 € / yö', note: 'sis. 2 henkilöä' },
            { item: 'Asuntovaunu lisähenkilö', price: '3 € / henkilö' },
            { item: 'Telttailu', price: '7 € / henkilö' },
          ],
        },
        {
          label: 'Muut',
          icon: '❄️',
          rows: [
            { item: 'Talvinen järvikuljetus', price: 'kysy hinta' },
          ],
        },
      ],
    },
    contact: {
      kicker: 'Yhteystiedot',
      title: 'Tule vierailulle tai ota yhteyttä',
      address: 'Pusin kylä, Alatskivin kunta, Tarton maakunta',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=58.64483549867105,27.166508285762042',
      locationLabel: 'Sijainti',
      hoursLabel: 'Aukioloajat',
      hours: 'Auki ympäri vuoden',
      phone: '+372 56 955 758',
      email: 'willipu.willipu@gmail.com',
      cta: 'Lähetä sähköposti',
      legal: {
        companyName: 'OÜ Willipu Turism',
        reg: '10972974',
        vat: 'EE100878462',
        legalAddress: 'Villipu, Pusi küla, 60217 Peipsiääre vald, Tartu maakond',
      },
    },
    floatContact: {
      tab: 'Kirjoita meille',
      title: 'Lähetä viesti',
      namePlaceholder: 'Nimesi',
      emailPlaceholder: 'Sähköpostisi',
      messagePlaceholder: 'Viestisi...',
      send: 'Avaa sähköpostiohjelma',
      hint: 'Napsauttamalla avautuu sähköpostiohjelmasi esitäytetyllä viestillä.',
      emailSubject: 'Kysely sivustolta willipu.ee — {name}',
      emailFrom: 'Nimi',
      emailReply: 'Vastausosoite',
    },
    footer: {
      tagline: 'Peipsijärven rannalla vuodesta 2010.',
      rights: 'Kaikki oikeudet pidätetään',
    },
  },
  lv: {
    nav: {
      about: 'Par mums',
      stay: 'Izmitināšana',
      amenities: 'Aktivitātes',
      pricing: 'Cenas',
      gallery: 'Galerija',
      contact: 'Kontakti',
    },
    hero: {
      eyebrow: 'Pie Peipusa ezera krasta',
      title: 'Willipu viesu nams un kempings',
      subtitle: 'Mierīga vieta pie ūdens — tikšanās, atpūtai un svinībām. Pusi ciemā, dienvidaustrumu Igaunijā.',
      cta: 'Rezervēt vietu kempingā',
      ctaAlt: 'Skatīt cenas',
      ctaNote: 'Istabu un namiņu rezervācijas pa e-pastu.',
    },
    about: {
      kicker: 'Laipni lūdzam',
      title: 'Vairāk nekā 20 gadu pieredze',
      body: 'Willipu atrodas Tartu novadā, Alatskivi pagastā, Pusi ciemā — tieši pie Peipusa ezera krasta. Tuvākā pilsēta Kallaste ir 2 km attālumā, Tartu — 50 km un Tallina — 200 km. Mēs piedāvājam istabas galvenajā mājā, vasarnamiņus, banketu zāli pasākumiem un pilnvērtīgu kempingu.',
      stats: [
        { value: '10', label: 'gultas galvenajā mājā' },
        { value: '30', label: 'vietas banketu zālē' },
        { value: '41', label: 'kempinga vietas' },
        { value: '2 km', label: 'līdz Kallastei' },
        { value: '16', label: 'gultas namiņos' },
        { value: 'līdz 5', label: 'papildu gultas' },
        { value: '🏖', label: 'bērniem draudzīgs smilšu pludmale' },
        { value: '🌿', label: 'liels zālājs āra pasākumiem' },
      ],
    },
    amenities: {
      kicker: 'Aktivitātes',
      title: 'Atpūtas iespējas pie ezera',
      items: [
        { icon: 'wave', title: 'Peldēšana un sērfošana', body: 'Smilšu pludmale, piemērota arī sērfotājiem.' },
        { icon: 'ball', title: 'Volejbols un spēles', body: 'Āra laukumi un brīvas zaļas zonas.' },
        { icon: 'fire', title: 'Ugunskurs un pirts', body: 'Ugunskura vieta un pirts grupām.' },
        { icon: 'hall', title: 'Banketu zāle 30 cilvēkiem', body: 'Konferences, svētki, apmācības.' },
        { icon: 'wifi', title: 'Ātrs WiFi visā teritorijā', body: 'Bezmaksas ātrs WiFi visā teritorijā.' },
      ],
    },
    pricing: {
      kicker: 'Cenas',
      title: 'Pieejamas cenas ar visām ērtībām',
      note: '50% avansa maksājums apstiprina rezervāciju. Atcelšanas gadījumā mazāk nekā 14 dienas pirms ierašanās avansa maksa netiek atgriezta.',
      downloadLabel: 'Lejupielādēt cenrādi (.xlsx)',
      groups: [
        {
          label: 'Lielais kempinga namiņš',
          icon: '🏡',
          photos: [
            { url: '/suur_kamp1.jpg', alt: 'Lielais kempinga namiņš' },
            { url: '/suur_kamp2.jpg', alt: 'Lielais kempinga namiņš' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Duša' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Virtuve' },
            { icon: 'grill', label: 'Grils' },
          ],
          rows: [
            { item: '5 cilvēkiem', price: '110 € / naktī' },
            { item: '4 cilvēkiem', price: '100 € / naktī' },
            { item: '2–3 cilvēkiem', price: '85 € / naktī' },
          ],
        },
        {
          label: 'Mazais kempinga namiņš',
          icon: '🛖',
          photos: [
            { url: '/v4.jpeg', alt: 'Mazais kempinga namiņš' },
            { url: '/v1.jpeg', alt: 'Mazais kempinga namiņš' },
            { url: '/v2.jpeg', alt: 'Mazais kempinga namiņš' },
            { url: '/v3.jpeg', alt: 'Mazais kempinga namiņš' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'grill', label: 'Grils' },
          ],
          rows: [
            { item: '2 cilvēkiem', price: '55 € / naktī' },
            { item: '1 cilvēkam', price: '35 € / naktī' },
          ],
        },
        {
          label: 'Galvenā māja - divvietīgs numurs',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Galvenā māja' },
            { url: '/peamaja%201.jpg', alt: 'Galvenā māja' },
            { url: '/peamaja%202.jpg', alt: 'Galvenā māja' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Virtuve' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Virtuve' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Duša' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Kopīgā virtuve' },
            { icon: 'grill', label: 'Grils' },
          ],
          rows: [
            { item: '2 cilvēkiem', price: '55 € / naktī' },
            { item: '1 cilvēkam', price: '35 € / naktī' },
          ],
        },
        {
          label: 'Galvenā māja - trīsvietīgs numurs',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Galvenā māja' },
            { url: '/peamaja%201.jpg', alt: 'Galvenā māja' },
            { url: '/peamaja%202.jpg', alt: 'Galvenā māja' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Virtuve' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Virtuve' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Duša' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Kopīgā virtuve' },
            { icon: 'grill', label: 'Grils' },
          ],
          rows: [
            { item: '3 cilvēkiem', price: '80 € / naktī' },
            { item: '2 cilvēkiem', price: '60 € / naktī' },
          ],
        },
        {
          label: 'Kempings 24/7',
          icon: '🚐',
          photos: [
            { url: '/kar1.jpg', alt: 'Kempings' },
            { url: '/kar2.jpg', alt: 'Kempings' },
            { url: '/kar3.jpg', alt: 'Kempings' },
            { url: '/kar4.jpg', alt: 'Kempings' },
          ],
          amenities: [
            { icon: 'checkin', label: 'Check-in 24/7', tooltip: 'Pašapkalpošanās reģistrācija' },
            { icon: 'electric', label: 'Elektrība' },
            { icon: 'shower', label: 'Duša' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'water', label: 'Tīrs ūdens' },
            { icon: 'dump', label: 'Notekūdeņu iztukšošana' },
            { icon: 'chemical', label: 'Ķīmiskais WC' },
            { icon: 'kitchen', label: 'Virtuve' },
            { icon: 'washer', label: 'Veļasmašīna' },
            { icon: 'trash', label: 'Atkritumu nodošana' },
            { icon: 'pets', label: 'Mājdzīvnieki atļauti' },
          ],
          rows: [
            { item: 'Kemperis bez elektrības', price: '20 € / naktī', note: 'ietver 2 cilvēkus' },
            { item: 'Kemperis ar elektrību', price: '25 € / naktī', note: 'ietver 2 cilvēkus' },
            { item: 'Kemperis papildu persona', price: '3 € / persona' },
            { item: 'Telšošana', price: '7 € / persona' },
          ],
        },
        {
          label: 'Citi',
          icon: '❄️',
          rows: [
            { item: 'Ziemas transportēšana pa ezeru', price: 'jautājiet cenu' },
          ],
        },
      ],
    },
    contact: {
      kicker: 'Kontakti',
      title: 'Apmeklējiet mūs vai sazinieties',
      address: 'Pusi ciems, Alatskivi pagasts, Tartu novads',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=58.64483549867105,27.166508285762042',
      locationLabel: 'Atrašanās vieta',
      hoursLabel: 'Darba laiks',
      hours: 'Atvērts visu gadu',
      phone: '+372 56 955 758',
      email: 'willipu.willipu@gmail.com',
      cta: 'Sūtīt e-pastu',
      legal: {
        companyName: 'OÜ Willipu Turism',
        reg: '10972974',
        vat: 'EE100878462',
        legalAddress: 'Villipu, Pusi küla, 60217 Peipsiääre vald, Tartu maakond',
      },
    },
    floatContact: {
      tab: 'Raksti mums',
      title: 'Sūtīt ziņojumu',
      namePlaceholder: 'Jūsu vārds',
      emailPlaceholder: 'Jūsu e-pasts',
      messagePlaceholder: 'Jūsu ziņojums...',
      send: 'Atvērt e-pasta lietotni',
      hint: 'Nospiežot atvērsies jūsu e-pasta lietotne ar aizpildītu ziņojumu.',
      emailSubject: 'Jautājums no willipu.ee — {name}',
      emailFrom: 'Vārds',
      emailReply: 'Atbildes adrese',
    },
    footer: {
      tagline: 'Pie Peipusa ezera kopš 2010. gada.',
      rights: 'Visas tiesības aizsargātas',
    },
  },
  lt: {
    nav: {
      about: 'Apie mus',
      stay: 'Nakvynė',
      amenities: 'Veikla',
      pricing: 'Kainos',
      gallery: 'Galerija',
      contact: 'Kontaktai',
    },
    hero: {
      eyebrow: 'Prie Peipaus ežero kranto',
      title: 'Willipu svečių namai ir kempingas',
      subtitle: 'Rami vieta prie vandens — susitikimams, poilsiui ir šventėms. Pusi kaime, pietų Estijoje.',
      cta: 'Rezervuoti vietą kempinge',
      ctaAlt: 'Žiūrėti kainas',
      ctaNote: 'Kambarių ir namelio rezervacijos el. paštu.',
    },
    about: {
      kicker: 'Sveiki atvykę',
      title: 'Daugiau nei 20 metų patirtis',
      body: 'Willipu yra Tartu apskrityje, Alatskivi seniūnijoje, Pusi kaime — tiesiai prie Peipaus ežero kranto. Artimiausias miestas Kallaste yra 2 km, Tartu — 50 km, Talinas — 200 km. Siūlome kambarius pagrindiniame name, vasarnamiukus, salę renginiams ir pilnavertį kempingą.',
      stats: [
        { value: '10', label: 'vietų pagrindiniame name' },
        { value: '30', label: 'vietų salėje' },
        { value: '41', label: 'kempingo aikštelių' },
        { value: '2 km', label: 'iki Kallaste' },
        { value: '16', label: 'vietų nameliuose' },
        { value: 'iki 5', label: 'papildomų vietų' },
        { value: '🏖', label: 'vaikams draugiškas smėlio paplūdimys' },
        { value: '🌿', label: 'didelis vejas lauko renginiams' },
      ],
    },
    amenities: {
      kicker: 'Veikla',
      title: 'Pramogos prie ežero',
      items: [
        { icon: 'wave', title: 'Plaukimas ir banglentė', body: 'Smėlio paplūdimys, tinkamas ir banglenčiams.' },
        { icon: 'ball', title: 'Tinklinis ir žaidimai', body: 'Lauko aikštelės ir atviros žolės erdvės.' },
        { icon: 'fire', title: 'Laužas ir pirtis', body: 'Laužavietė ir pirtis grupėms.' },
        { icon: 'hall', title: 'Salė 30 žmonių', body: 'Konferencijos, šventės, mokymai.' },
        { icon: 'wifi', title: 'Greitas WiFi visoje teritorijoje', body: 'Nemokamas greitas WiFi visoje teritorijoje.' },
      ],
    },
    pricing: {
      kicker: 'Kainos',
      title: 'Prieinamos kainos su visais patogumais',
      note: '50% išankstinis mokėjimas patvirtina rezervaciją. Atšaukus rezervaciją likus mažiau nei 14 dienų iki atvykimo, avansas negrąžinamas.',
      downloadLabel: 'Atsisiųsti kainoraštį (.xlsx)',
      groups: [
        {
          label: 'Didelis kempingo namelis',
          icon: '🏡',
          photos: [
            { url: '/suur_kamp1.jpg', alt: 'Didelis kempingo namelis' },
            { url: '/suur_kamp2.jpg', alt: 'Didelis kempingo namelis' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Dušas' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Virtuvė' },
            { icon: 'grill', label: 'Grilis' },
          ],
          rows: [
            { item: '5 asmenims', price: '110 € / naktis' },
            { item: '4 asmenims', price: '100 € / naktis' },
            { item: '2–3 asmenims', price: '85 € / naktis' },
          ],
        },
        {
          label: 'Mažas kempingo namelis',
          icon: '🛖',
          photos: [
            { url: '/v4.jpeg', alt: 'Mažas kempingo namelis' },
            { url: '/v1.jpeg', alt: 'Mažas kempingo namelis' },
            { url: '/v2.jpeg', alt: 'Mažas kempingo namelis' },
            { url: '/v3.jpeg', alt: 'Mažas kempingo namelis' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'grill', label: 'Grilis' },
          ],
          rows: [
            { item: '2 asmenims', price: '55 € / naktis' },
            { item: '1 asmeniui', price: '35 € / naktis' },
          ],
        },
        {
          label: 'Pagrindinis namas - dvivietis kambarys',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Pagrindinis namas' },
            { url: '/peamaja%201.jpg', alt: 'Pagrindinis namas' },
            { url: '/peamaja%202.jpg', alt: 'Pagrindinis namas' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Virtuvė' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Virtuvė' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Dušas' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Bendra virtuvė' },
            { icon: 'grill', label: 'Grilis' },
          ],
          rows: [
            { item: '2 asmenims', price: '55 € / naktis' },
            { item: '1 asmeniui', price: '35 € / naktis' },
          ],
        },
        {
          label: 'Pagrindinis namas - trivietis kambarys',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Pagrindinis namas' },
            { url: '/peamaja%201.jpg', alt: 'Pagrindinis namas' },
            { url: '/peamaja%202.jpg', alt: 'Pagrindinis namas' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Virtuvė' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Virtuvė' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Dušas' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Bendra virtuvė' },
            { icon: 'grill', label: 'Grilis' },
          ],
          rows: [
            { item: '3 asmenims', price: '80 € / naktis' },
            { item: '2 asmenims', price: '60 € / naktis' },
          ],
        },
        {
          label: 'Kempingas 24/7',
          icon: '🚐',
          photos: [
            { url: '/kar1.jpg', alt: 'Kempingas' },
            { url: '/kar2.jpg', alt: 'Kempingas' },
            { url: '/kar3.jpg', alt: 'Kempingas' },
            { url: '/kar4.jpg', alt: 'Kempingas' },
          ],
          amenities: [
            { icon: 'checkin', label: 'Check-in 24/7', tooltip: 'Savitarnos registracija' },
            { icon: 'electric', label: 'Elektra' },
            { icon: 'shower', label: 'Dušas' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'water', label: 'Gėlas vanduo' },
            { icon: 'dump', label: 'Nuotekų išleidimas' },
            { icon: 'chemical', label: 'Cheminis WC' },
            { icon: 'kitchen', label: 'Virtuvė' },
            { icon: 'washer', label: 'Skalbimo mašina' },
            { icon: 'trash', label: 'Atliekų tvarkymas' },
            { icon: 'pets', label: 'Augintiniai leidžiami' },
          ],
          rows: [
            { item: 'Kemperis be elektros', price: '20 € / naktis', note: 'apima 2 asmenis' },
            { item: 'Kemperis su elektra', price: '25 € / naktis', note: 'apima 2 asmenis' },
            { item: 'Kemperio papildomas asmuo', price: '3 € / asmuo' },
            { item: 'Palapinė', price: '7 € / asmuo' },
          ],
        },
        {
          label: 'Kita',
          icon: '❄️',
          rows: [
            { item: 'Žiemos transportavimas per ežerą', price: 'teiraukitės kainos' },
          ],
        },
      ],
    },
    contact: {
      kicker: 'Kontaktai',
      title: 'Apsilankykite arba susisiekite',
      address: 'Pusi kaimas, Alatskivi seniūnija, Tartu apskritis',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=58.64483549867105,27.166508285762042',
      locationLabel: 'Vieta',
      hoursLabel: 'Darbo laikas',
      hours: 'Atidaryta ištisus metus',
      phone: '+372 56 955 758',
      email: 'willipu.willipu@gmail.com',
      cta: 'Siųsti el. laišką',
      legal: {
        companyName: 'OÜ Willipu Turism',
        reg: '10972974',
        vat: 'EE100878462',
        legalAddress: 'Villipu, Pusi küla, 60217 Peipsiääre vald, Tartu maakond',
      },
    },
    floatContact: {
      tab: 'Rašyk mums',
      title: 'Siųsti žinutę',
      namePlaceholder: 'Jūsų vardas',
      emailPlaceholder: 'Jūsų el. paštas',
      messagePlaceholder: 'Jūsų žinutė...',
      send: 'Atidaryti el. pašto programą',
      hint: 'Paspaudus atsidarys jūsų el. pašto programa su iš anksto užpildyta žinute.',
      emailSubject: 'Klausimas iš willipu.ee — {name}',
      emailFrom: 'Vardas',
      emailReply: 'Atsakymo adresas',
    },
    footer: {
      tagline: 'Prie Peipaus ežero nuo 2010 m.',
      rights: 'Visos teisės saugomos',
    },
  },
  ru: {
    nav: {
      about: 'О нас',
      stay: 'Размещение',
      amenities: 'Активности',
      pricing: 'Цены',
      gallery: 'Галерея',
      contact: 'Контакты',
    },
    hero: {
      eyebrow: 'На берегу Чудского озера',
      title: 'Гостевой дом и кемпинг Willipu',
      subtitle: 'Тихое место у воды — для встреч, отдыха и праздников. Тартумаа, деревня Пуси.',
      cta: 'Забронировать кемпинг',
      ctaAlt: 'Посмотреть цены',
      ctaNote: 'Бронирование номеров и коттеджей по электронной почте.',
    },
    about: {
      kicker: 'Добро пожаловать',
      title: 'Более 20 лет опыта',
      body: 'Willipu расположен в Тартумаа, волости Алатскиви, деревне Пуси, прямо на берегу Чудского озера. Ближайший город Каллясте находится в 2 км, Тарту — в 50 км, Таллин — в 200 км. Мы предлагаем номера в главном доме, летние коттеджи, банкетный зал для мероприятий и кемпинг для домов на колёсах.',
      stats: [
        { value: '10', label: 'мест в главном доме' },
        { value: '30', label: 'мест в банкетном зале' },
        { value: '41', label: 'место для дома на колёсах' },
        { value: '2 км', label: 'до г. Каллясте' },
        { value: '16', label: 'мест в коттеджах' },
        { value: 'до 5', label: 'доп. мест' },
        { value: '🏖', label: 'детский пляж с песком' },
        { value: '🌿', label: 'большая лужайка для мероприятий' },
      ],
    },
    stay: {
      kicker: 'Размещение',
      title: 'Выберите подходящий вариант',
      cards: [
        {
          name: 'Главный дом',
          tagline: 'Номера на 2–3 человека, до 10 гостей',
          desc: 'В трёх номерах есть TV, WiFi, душ и WC. В одном номере душ и WC общие. На первом этаже — банкетный зал до 30 человек.',
          price: 'от 25 € / чел.',
        },
        {
          name: 'Большой коттедж',
          tagline: '5 спальных мест, кухня, душ, WC',
          desc: 'Две комнаты, WC, душ и кухня. Кондиционер. Подходит для семьи или небольшой группы.',
          price: '110 € / ночь',
        },
        {
          name: 'Малый коттедж',
          tagline: '2 спальных места, утеплённый',
          desc: 'Используется зимой, с горячей водой и WC. Уютное место для пары или дополнительное размещение.',
          price: '40 € / ночь',
        },
        {
          name: 'Кемпинг',
          tagline: 'Электричество, вода, душ, WC',
          desc: 'До 41 места для домов на колёсах с подключением к электричеству, воде и канализации. Палатки разрешены.',
          price: 'от 14 € / ночь',
        },
      ],
    },
    amenities: {
      kicker: 'Чем заняться',
      title: 'Активности у воды',
      items: [
        { icon: 'wave', title: 'Купание и сёрфинг', body: 'Песчаный пляж, подходит и для сёрфинга.' },
        { icon: 'ball', title: 'Волейбол и игры', body: 'Спортплощадки и открытые травяные поля.' },
        { icon: 'fire', title: 'Костёр и сауна', body: 'Место для костра и сауна для компании.' },
        { icon: 'hall', title: 'Банкетный зал до 30 чел.', body: 'Конференции, вечеринки, тренинги.' },
        { icon: 'wifi', title: 'Быстрый WiFi по всей территории', body: 'Бесплатный быстрый WiFi по всей территории.' },
      ],
    },
    pricing: {
      kicker: 'Цены',
      title: 'Доступные цены со всеми удобствами',
      note: 'Для подтверждения бронирования вносится предоплата 50%. При отмене менее чем за 14 дней предоплата не возвращается.',
      downloadLabel: 'Скачать прайс-лист (.xlsx)',
      groups: [
        {
          label: 'Большой коттедж',
          icon: '🏡',
          photos: [
            { url: '/suur_kamp1.jpg', alt: 'Большой коттедж' },
            { url: '/suur_kamp2.jpg', alt: 'Большой коттедж' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Душ' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Кухня' },
            { icon: 'grill', label: 'Гриль' },
          ],
          rows: [
            { item: '5 человек', price: '110 € / ночь' },
            { item: '4 человека', price: '100 € / ночь' },
            { item: '2–3 человека', price: '85 € / ночь' },
          ],
        },
        {
          label: 'Малый коттедж',
          icon: '🛖',
          photos: [
            { url: '/v4.jpeg', alt: 'Малый коттедж' },
            { url: '/v1.jpeg', alt: 'Малый коттедж' },
            { url: '/v2.jpeg', alt: 'Малый коттедж' },
            { url: '/v3.jpeg', alt: 'Малый коттедж' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'grill', label: 'Гриль' },
          ],
          rows: [
            { item: '2 человека', price: '55 € / ночь' },
            { item: '1 человек', price: '35 € / ночь' },
          ],
        },
        {
          label: 'Главный дом - двухместный номер',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Главный дом' },
            { url: '/peamaja%201.jpg', alt: 'Главный дом' },
            { url: '/peamaja%202.jpg', alt: 'Главный дом' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Кухня' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Кухня' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Душ' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Общая кухня' },
            { icon: 'grill', label: 'Гриль' },
          ],
          rows: [
            { item: '2 человека', price: '55 € / ночь' },
            { item: '1 человек', price: '35 € / ночь' },
          ],
        },
        {
          label: 'Главный дом - трёхместный номер',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Главный дом' },
            { url: '/peamaja%201.jpg', alt: 'Главный дом' },
            { url: '/peamaja%202.jpg', alt: 'Главный дом' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Кухня' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Кухня' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Душ' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Общая кухня' },
            { icon: 'grill', label: 'Гриль' },
          ],
          rows: [
            { item: '3 человека', price: '80 € / ночь' },
            { item: '2 человека', price: '60 € / ночь' },
          ],
        },
        {
          label: 'Кемпинг 24/7',
          icon: '🚐',
          photos: [
            { url: '/kar1.jpg', alt: 'Кемпинг' },
            { url: '/kar2.jpg', alt: 'Кемпинг' },
            { url: '/kar3.jpg', alt: 'Кемпинг' },
            { url: '/kar4.jpg', alt: 'Кемпинг' },
          ],
          amenities: [
            { icon: 'checkin', label: 'Заезд 24/7', tooltip: 'Самостоятельный заезд' },
            { icon: 'electric', label: 'Электричество' },
            { icon: 'shower', label: 'Душ' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'water', label: 'Чистая вода' },
            { icon: 'dump', label: 'Слив отходов' },
            { icon: 'chemical', label: 'Хим. туалет' },
            { icon: 'kitchen', label: 'Кухня' },
            { icon: 'washer', label: 'Стиральная машина' },
            { icon: 'trash', label: 'Вывоз мусора' },
            { icon: 'pets', label: 'Питомцы разрешены' },
          ],
          rows: [
            { item: 'Дом на колёсах без электричества', price: '20 € / ночь', note: 'включено 2 чел.' },
            { item: 'Дом на колёсах с электричеством', price: '25 € / ночь', note: 'включено 2 чел.' },
            { item: 'Доп. человек для дома на колёсах', price: '3 € / чел.' },
            { item: 'Палатка', price: '7 € / чел.' },
          ],
        },
        {
          label: 'Прочее',
          icon: '❄️',
          rows: [
            { item: 'Зимний транспорт по озеру', price: 'уточнить цену' },
          ],
        },
      ],
    },
    contact: {
      kicker: 'Контакты',
      title: 'Приезжайте или свяжитесь с нами',
      address: 'Деревня Пуси, волость Алатскиви, Тартумаа',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=58.64483549867105,27.166508285762042',
      locationLabel: 'Адрес',
      hoursLabel: 'Часы работы',
      hours: 'Открыто круглый год',
      phone: '+372 56 955 758',
      email: 'willipu.willipu@gmail.com',
      cta: 'Написать письмо',
      legal: {
        companyName: 'OÜ Willipu Turism',
        reg: '10972974',
        vat: 'EE100878462',
        legalAddress: 'Villipu, Pusi küla, 60217 Peipsiääre vald, Tartu maakond',
      },
    },
    floatContact: {
      tab: 'Напишите нам',
      title: 'Написать нам',
      namePlaceholder: 'Ваше имя',
      emailPlaceholder: 'Ваш e-mail',
      messagePlaceholder: 'Ваше сообщение...',
      send: 'Открыть почтовый клиент',
      hint: 'Нажатие откроет ваш почтовый клиент с готовым письмом.',
      emailSubject: 'Запрос с willipu.ee — {name}',
      emailFrom: 'Имя',
      emailReply: 'Адрес для ответа',
    },
    footer: {
      tagline: 'На берегу Чудского озера с 2010 года.',
      rights: 'Все права защищены',
    },
  },
}

export const gallery = [
  {
    url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&q=80',
    alt: 'Lake at sunrise',
  },
  {
    url: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=1200&q=80',
    alt: 'Wooden cottage in trees',
  },
  {
    url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80',
    alt: 'Misty forest morning',
  },
  {
    url: 'https://images.unsplash.com/photo-1499696010180-025ef6e1a8f9?w=1200&q=80',
    alt: 'Cabin interior with wood',
  },
  {
    url: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=1200&q=80',
    alt: 'Pine forest by water',
  },
  {
    url: 'https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=1200&q=80',
    alt: 'Boat dock at golden hour',
  },
]

export const heroImage = '/52c0d4c0-7aea-429a-b0f0-0f4a1ca2155d.jpg'
