export const content = {
  et: {
    nav: {
      about: 'Meist',
      amenities: 'Tegevused',
      pricing: 'Hinnakiri',
      contact: 'Kontakt',
    },
    hero: {
      eyebrow: 'Peipsi järve kaldal',
      title: 'Willipu külalisemaja ja karavanipark',
      subtitle:
        'Vaikne paik vee ääres — kohtumiseks, puhkuseks ja peoks. Tartumaal, Pusi külas.',
      cta: 'Broneeri ööbimine karavanipargis',
      ctaAlt: 'Vaata hindu',
      ctaNote: 'Tubade ja kämpingute broneerimine emaili teel.',
    },
    about: {
      kicker: 'Tere tulemast',
      title: 'Üle 20 aasta kogemusi',
      body:
        'Willipu asub Tartumaal, Alatskivi vallas, Pusi külas, otse Peipsi järve kaldal. Lähim linn Kallaste jääb 2 km kaugusele, Tartu 50 km ja Tallinn 200 km kaugusele. Pakume majutust nii peamajas kui ka suvemajakestes, ruumi pidudeks ja koolitusteks ning kohta haagissuvilatele.',
      stats: [
        { value: '41', label: 'haagissuvila kohta' },
        { value: '10', label: 'kohta peamajas' },
        { value: '30', label: 'kohta peosaalis' },
        { value: '16', label: 'kohta kämpingumajades' },
        { value: 'kuni 5', label: 'lisakohta' },
        { value: '🏖', label: 'lapsesõbralik liivarand' },
        { value: '🌿', label: 'suur muruplats väliürituste korraldamiseks' },
        { value: '2 km', label: 'Kallaste linna' },
      ],
    },
    amenities: {
      kicker: 'Mida teha',
      title: 'Tegevused vee ääres',
      items: [
        { icon: 'wave', title: 'Ujumine ja surf', body: 'Liivane rand, sobib ka surfaritele.' },
        { icon: 'ball', title: 'Võrkpall ja mängud', body: 'Õueplatsid ja vabad muruväljakud.' },
        { icon: 'fire', title: 'Lõke ja saun', body: 'Lõkkeplats ning saun seltskonnale.' },
        { icon: 'hall', title: 'Peosaal kuni 30', body: 'Konverentsid, peod, koolitused.' },
        { icon: 'wifi', title: 'Kiire WiFi kogu territooriumil', body: 'Tasuta ühendus nii toas kui õuealal.' },
      ],
    },
    pricing: {
      kicker: 'Hinnakiri',
      title: 'Soodsad hinnad, kõigi mugavustega',
      note:
        'Broneeringu kinnitamiseks tasutakse 50% ettemaksuna. Tühistamisel alla 14 päeva ettemaks ei tagastata.',
      downloadLabel: 'Laadi hinnakiri alla (.xlsx)',
      groups: [
        {
          label: 'Suur kämpingumaja',
          icon: '🏡',
          photos: [
            { url: '/suur_kamp1.jpg', alt: 'Suur kämpingumaja' },
            { url: '/suur_kamp2.jpg', alt: 'Suur kämpingumaja' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Dušš' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Köök' },
            { icon: 'grill', label: 'Grill' },
          ],
          rows: [
            { item: '5 inimesele', price: '110 € / öö' },
            { item: '4 inimesele', price: '100 € / öö' },
            { item: '2–3 inimesele', price: '85 € / öö' },
          ],
        },
        {
          label: 'Väike kämpingumaja',
          icon: '🛖',
          photos: [
            { url: '/v4.jpeg', alt: 'Väike kämpingumaja' },
            { url: '/v1.jpeg', alt: 'Väike kämpingumaja' },
            { url: '/v2.jpeg', alt: 'Väike kämpingumaja' },
            { url: '/v3.jpeg', alt: 'Väike kämpingumaja' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'grill', label: 'Grill' },
          ],
          rows: [
            { item: '2 inimesele', price: '55 € / öö' },
            { item: '1 inimesele', price: '35 € / öö' },
          ],
        },
        {
          label: 'Peamaja - kahene tuba',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Peamaja' },
            { url: '/peamaja%201.jpg', alt: 'Peamaja' },
            { url: '/peamaja%202.jpg', alt: 'Peamaja' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Köök' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Köök' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Dušš' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Ühine köök' },
            { icon: 'grill', label: 'Grill' },
          ],
          rows: [
            { item: '2 inimesele', price: '55 € / öö' },
            { item: '1 inimesele', price: '35 € / öö' },
          ],
        },
        {
          label: 'Peamaja - kolmene tuba',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Peamaja' },
            { url: '/peamaja%201.jpg', alt: 'Peamaja' },
            { url: '/peamaja%202.jpg', alt: 'Peamaja' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Köök' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Köök' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Dušš' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Ühine köök' },
            { icon: 'grill', label: 'Grill' },
          ],
          rows: [
            { item: '3 inimesele', price: '80 € / öö' },
            { item: '2 inimesele', price: '60 € / öö' },
          ],
        },
        {
          label: 'Karavanipark 24/7',
          icon: '🚐',
          photos: [
            { url: '/kar1.jpg', alt: 'Karavanipark' },
            { url: '/kar2.jpg', alt: 'Karavanipark' },
            { url: '/kar3.jpg', alt: 'Karavanipark' },
            { url: '/kar4.jpg', alt: 'Karavanipark' },
          ],
          amenities: [
            { icon: 'checkin', label: 'Check-in 24/7', tooltip: 'Iseteeninduslik check-in' },
            { icon: 'electric', label: 'Elekter' },
            { icon: 'shower', label: 'Dušš' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'water', label: 'Puhas vesi' },
            { icon: 'dump', label: 'Purgimine' },
            { icon: 'chemical', label: 'Keemiline WC' },
            { icon: 'kitchen', label: 'Köök' },
            { icon: 'washer', label: 'Pesumasin' },
            { icon: 'trash', label: 'Prügi äraandmine' },
            { icon: 'pets', label: 'Lemmikloomad lubatud' },
          ],
          rows: [
            { item: 'Haagissuvila ilma elektrita', price: '20 € / öö', note: 'sisaldab 2 inimest' },
            { item: 'Haagissuvila elektriga', price: '25 € / öö', note: 'sisaldab 2 inimest' },
            { item: 'Haagissuvila lisa inimene', price: '3 € / inimene' },
            { item: 'Telkimine', price: '7 € / inimene' },
          ],
          badges: {
            checkin: {
              title: 'Automaatne sissepääs 24/7',
              body: 'Parki saab sõita igal ajal — tõkepuu avaneb online-broneeringuga saadud koodiga. Broneeri, maksa ja registreeri end iseseisvalt pargihaldur.ee kaudu.',
              linkLabel: 'Broneeri · pargihaldur.ee',
              linkUrl: 'https://willipu.pargihaldur.ee',
            },
            electric: {
              title: 'Elektriühendus · kuni 10 A',
              body: 'Maksimaalne lubatud võimsus ühe karavani kohta on 10 A. Soojapuhurite ja föönide kasutamine pole lubatud. Kasutatavad elektriseadmed peavad olema korras ning ühendusjuhtmete isolatsioon terve.',
            },
            water: {
              title: 'Puhas vesi karavanide veepaakide täitmiseks',
              body: 'Meelespea: Kuumal suvepäeval lase veel joosta vähemalt 3 minutit, et veevoolikus olev vesi asenduks värskega.',
            },
          },
        },
        {
          label: 'Muud',
          icon: '❄️',
          rows: [
            { item: 'Talvine järvetransport', price: 'küsi hinda' },
          ],
        },
      ],
    },
    contact: {
      kicker: 'Kontakt',
      title: 'Tule külla või võta ühendust',
      address: 'Pusi küla, Alatskivi vald, Tartumaa',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=58.64483549867105,27.166508285762042',
      locationLabel: 'Asukoht',
      hoursLabel: 'Lahtiolekuajad',
      hours: 'Avatud aastaringselt',
      phone: '+372 56 955 758',
      email: 'willipu.willipu@gmail.com',
      cta: 'Saada e-kiri',
      legal: {
        companyName: 'OÜ Willipu Turism',
        reg: '10972974',
        vat: 'EE100878462',
        legalAddress: 'Villipu, Pusi küla, 60217 Peipsiääre vald, Tartu maakond',
        bankLabel: 'Pangakonto',
        iban: 'EE402200221023806138',
        bank: 'Swedbank AS',
        swift: 'HABAEE2X',
      },
    },
    footer: {
      tagline: 'Peipsi järve ääres alates 2010.',
      rights: 'Kõik õigused kaitstud',
    },
  },
  en: {
    nav: {
      about: 'About',
      amenities: 'Activities',
      pricing: 'Pricing',
      contact: 'Contact',
    },
    hero: {
      eyebrow: 'On the shore of Lake Peipus',
      title: 'Willipu Guesthouse and Caravan Park',
      subtitle:
        'A quiet place by the water — for gatherings, getaways and good food. In Pusi village, southern Estonia.',
      cta: 'Book a stay at the caravan park',
      ctaAlt: 'See pricing',
      ctaNote: 'Room and cottage bookings by email.',
    },
    about: {
      kicker: 'Welcome',
      title: 'Over 20 years of experience',
      body:
        'Willipu sits in Tartu county, Alatskivi commune, Pusi village — right on the shore of Lake Peipus. The nearest town Kallaste is 2 km away, Tartu is 50 km, Tallinn 200 km. We offer rooms in the main house, summer cottages, a banquet hall for events and a full caravan park.',
      stats: [
        { value: '41', label: 'caravan spots' },
        { value: '10', label: 'beds in main house' },
        { value: '30', label: 'seats in banquet hall' },
        { value: '16', label: 'beds in cottages' },
        { value: 'up to 5', label: 'extra beds' },
        { value: '🏖', label: 'child-friendly sandy beach' },
        { value: '🌿', label: 'large lawn for outdoor events' },
        { value: '2 km', label: 'to Kallaste' },
      ],
    },
    amenities: {
      kicker: 'Things to do',
      title: 'Life by the lake',
      items: [
        { icon: 'wave', title: 'Swim and surf', body: 'Sandy beach, also great for windsurfers.' },
        { icon: 'ball', title: 'Volleyball and games', body: 'Outdoor courts and open lawns.' },
        { icon: 'fire', title: 'Bonfire and sauna', body: 'Fire pit and sauna for groups.' },
        { icon: 'hall', title: 'Banquet hall for 30', body: 'Conferences, parties, trainings.' },
        { icon: 'wifi', title: 'Fast WiFi across the property', body: 'Free connection indoors and throughout the grounds.' },
      ],
    },
    pricing: {
      kicker: 'Pricing',
      title: 'Affordable prices, all comforts included',
      note:
        'A 50% deposit confirms your booking. Cancellations within 14 days of arrival forfeit the deposit.',
      downloadLabel: 'Download price list (.xlsx)',
      groups: [
        {
          label: 'Large Camping Cottage',
          icon: '🏡',
          photos: [
            { url: '/suur_kamp1.jpg', alt: 'Large Camping Cottage' },
            { url: '/suur_kamp2.jpg', alt: 'Large Camping Cottage' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Shower' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Kitchen' },
            { icon: 'grill', label: 'BBQ' },
          ],
          rows: [
            { item: '5 persons', price: '€110 / night' },
            { item: '4 persons', price: '€100 / night' },
            { item: '2–3 persons', price: '€85 / night' },
          ],
        },
        {
          label: 'Small Camping Cottage',
          icon: '🛖',
          photos: [
            { url: '/v4.jpeg', alt: 'Small Camping Cottage' },
            { url: '/v1.jpeg', alt: 'Small Camping Cottage' },
            { url: '/v2.jpeg', alt: 'Small Camping Cottage' },
            { url: '/v3.jpeg', alt: 'Small Camping Cottage' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'grill', label: 'BBQ' },
          ],
          rows: [
            { item: '2 persons', price: '€55 / night' },
            { item: '1 person', price: '€35 / night' },
          ],
        },
        {
          label: 'Main house - double room',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Main house' },
            { url: '/peamaja%201.jpg', alt: 'Main house' },
            { url: '/peamaja%202.jpg', alt: 'Main house' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Kitchen' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Kitchen' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Shower' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Shared kitchen' },
            { icon: 'grill', label: 'BBQ' },
          ],
          rows: [
            { item: '2 persons', price: '€55 / night' },
            { item: '1 person', price: '€35 / night' },
          ],
        },
        {
          label: 'Main house - triple room',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Main house' },
            { url: '/peamaja%201.jpg', alt: 'Main house' },
            { url: '/peamaja%202.jpg', alt: 'Main house' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Kitchen' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Kitchen' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Shower' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Shared kitchen' },
            { icon: 'grill', label: 'BBQ' },
          ],
          rows: [
            { item: '3 persons', price: '€80 / night' },
            { item: '2 persons', price: '€60 / night' },
          ],
        },
        {
          label: 'Caravan Park 24/7',
          icon: '🚐',
          photos: [
            { url: '/kar1.jpg', alt: 'Caravan Park' },
            { url: '/kar2.jpg', alt: 'Caravan Park' },
            { url: '/kar3.jpg', alt: 'Caravan Park' },
            { url: '/kar4.jpg', alt: 'Caravan Park' },
          ],
          amenities: [
            { icon: 'checkin', label: 'Check-in 24/7', tooltip: 'Self-service check-in' },
            { icon: 'electric', label: 'Electric' },
            { icon: 'shower', label: 'Shower' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'water', label: 'Fresh water' },
            { icon: 'dump', label: 'Waste dump' },
            { icon: 'chemical', label: 'Chemical WC' },
            { icon: 'kitchen', label: 'Kitchen' },
            { icon: 'washer', label: 'Washer' },
            { icon: 'trash', label: 'Waste disposal' },
            { icon: 'pets', label: 'Pets welcome' },
          ],
          rows: [
            { item: 'Caravan without power', price: '€20 / night', note: 'includes 2 persons' },
            { item: 'Caravan with power', price: '€25 / night', note: 'includes 2 persons' },
            { item: 'Caravan extra person', price: '€3 / person' },
            { item: 'Tent camping', price: '€7 / person' },
          ],
          badges: {
            checkin: {
              title: 'Automated 24/7 access',
              body: 'Arrive whenever it suits you — the barrier opens with a code sent at booking. Book, pay and check in independently at pargihaldur.ee.',
              linkLabel: 'Book · pargihaldur.ee',
              linkUrl: 'https://willipu.pargihaldur.ee',
            },
            electric: {
              title: 'Electric hook-up · max 10 A',
              body: 'Maximum permitted load per caravan is 10 A. Fan heaters and hair dryers are not permitted. All electrical appliances must be in good working order and cable insulation must be intact.',
            },
            water: {
              title: 'Fresh water for filling caravan tanks',
              body: 'Reminder: On a hot summer day, let the water run for at least 3 minutes so that the water standing in the hose is replaced with fresh water.',
            },
          },
        },
        {
          label: 'Other',
          icon: '❄️',
          rows: [
            { item: 'Winter lake transport', price: 'ask for price' },
          ],
        },
      ],
    },
    contact: {
      kicker: 'Contact',
      title: 'Come visit or get in touch',
      address: 'Pusi village, Alatskivi parish, Tartu county',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=58.64483549867105,27.166508285762042',
      locationLabel: 'Location',
      hoursLabel: 'Opening hours',
      hours: 'Open year-round',
      phone: '+372 56 955 758',
      email: 'willipu.willipu@gmail.com',
      cta: 'Send an email',
      legal: {
        companyName: 'OÜ Willipu Turism',
        reg: '10972974',
        vat: 'EE100878462',
        legalAddress: 'Villipu, Pusi küla, 60217 Peipsiääre vald, Tartu maakond',
        bankLabel: 'Bank account',
        iban: 'EE402200221023806138',
        bank: 'Swedbank AS',
        swift: 'HABAEE2X',
      },
    },
    footer: {
      tagline: 'On Lake Peipus since 2010.',
      rights: 'All rights reserved',
    },
  },
  de: {
    nav: {
      about: 'Über uns',
      amenities: 'Aktivitäten',
      pricing: 'Preise',
      contact: 'Kontakt',
    },
    hero: {
      eyebrow: 'Am Ufer des Peipussees',
      title: 'Willipu Gästehaus und Campingpark',
      subtitle: 'Ein ruhiger Ort am Wasser — zum Treffen, Erholen und Feiern. Im Dorf Pusi, Südestland.',
      cta: 'Stellplatz im Campingpark buchen',
      ctaAlt: 'Preise ansehen',
      ctaNote: 'Zimmer- und Hüttenbuchungen per E-Mail.',
    },
    about: {
      kicker: 'Willkommen',
      title: 'Über 20 Jahre Erfahrung',
      body: 'Willipu liegt im Kreis Tartu, Gemeinde Alatskivi, Dorf Pusi — direkt am Ufer des Peipussees. Die nächste Stadt Kallaste ist 2 km entfernt, Tartu 50 km und Tallinn 200 km. Wir bieten Zimmer im Haupthaus, Sommerhütten, einen Festsaal für Veranstaltungen und einen vollständigen Campingpark.',
      stats: [
        { value: '41', label: 'Campingstellplätze' },
        { value: '10', label: 'Betten im Haupthaus' },
        { value: '30', label: 'Plätze im Festsaal' },
        { value: '16', label: 'Betten in Hütten' },
        { value: 'bis 5', label: 'Zusatzbetten' },
        { value: '🏖', label: 'kinderfreundlicher Sandstrand' },
        { value: '🌿', label: 'großer Rasen für Freiluftveranstaltungen' },
        { value: '2 km', label: 'bis Kallaste' },
      ],
    },
    amenities: {
      kicker: 'Aktivitäten',
      title: 'Freizeitangebote am See',
      items: [
        { icon: 'wave', title: 'Schwimmen und Surfen', body: 'Sandstrand, ideal auch für Windsurfer.' },
        { icon: 'ball', title: 'Volleyball und Spiele', body: 'Außenplätze und offene Rasenflächen.' },
        { icon: 'fire', title: 'Lagerfeuer und Sauna', body: 'Feuerstelle und Sauna für Gruppen.' },
        { icon: 'hall', title: 'Festsaal für 30', body: 'Konferenzen, Feiern, Schulungen.' },
        { icon: 'wifi', title: 'Schnelles WLAN auf dem gesamten Gelände', body: 'Kostenlose Verbindung im Haus und im Außenbereich.' },
      ],
    },
    pricing: {
      kicker: 'Preise',
      title: 'Günstige Preise, alle Annehmlichkeiten inklusive',
      note: 'Eine Anzahlung von 50 % bestätigt Ihre Buchung. Bei Stornierung innerhalb von 14 Tagen vor Anreise verfällt die Anzahlung.',
      downloadLabel: 'Preisliste herunterladen (.xlsx)',
      groups: [
        {
          label: 'Großes Campinghaus',
          icon: '🏡',
          photos: [
            { url: '/suur_kamp1.jpg', alt: 'Großes Campinghaus' },
            { url: '/suur_kamp2.jpg', alt: 'Großes Campinghaus' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Dusche' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Küche' },
            { icon: 'grill', label: 'Grill' },
          ],
          rows: [
            { item: '5 Personen', price: '110 € / Nacht' },
            { item: '4 Personen', price: '100 € / Nacht' },
            { item: '2–3 Personen', price: '85 € / Nacht' },
          ],
        },
        {
          label: 'Kleines Campinghaus',
          icon: '🛖',
          photos: [
            { url: '/v4.jpeg', alt: 'Kleines Campinghaus' },
            { url: '/v1.jpeg', alt: 'Kleines Campinghaus' },
            { url: '/v2.jpeg', alt: 'Kleines Campinghaus' },
            { url: '/v3.jpeg', alt: 'Kleines Campinghaus' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'grill', label: 'Grill' },
          ],
          rows: [
            { item: '2 Personen', price: '55 € / Nacht' },
            { item: '1 Person', price: '35 € / Nacht' },
          ],
        },
        {
          label: 'Haupthaus - Doppelzimmer',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Haupthaus' },
            { url: '/peamaja%201.jpg', alt: 'Haupthaus' },
            { url: '/peamaja%202.jpg', alt: 'Haupthaus' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Küche' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Küche' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Dusche' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Gemeinschaftsküche' },
            { icon: 'grill', label: 'Grill' },
          ],
          rows: [
            { item: '2 Personen', price: '55 € / Nacht' },
            { item: '1 Person', price: '35 € / Nacht' },
          ],
        },
        {
          label: 'Haupthaus - Dreibettzimmer',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Haupthaus' },
            { url: '/peamaja%201.jpg', alt: 'Haupthaus' },
            { url: '/peamaja%202.jpg', alt: 'Haupthaus' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Küche' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Küche' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Dusche' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Gemeinschaftsküche' },
            { icon: 'grill', label: 'Grill' },
          ],
          rows: [
            { item: '3 Personen', price: '80 € / Nacht' },
            { item: '2 Personen', price: '60 € / Nacht' },
          ],
        },
        {
          label: 'Campingpark 24/7',
          icon: '🚐',
          photos: [
            { url: '/kar1.jpg', alt: 'Campingpark' },
            { url: '/kar2.jpg', alt: 'Campingpark' },
            { url: '/kar3.jpg', alt: 'Campingpark' },
            { url: '/kar4.jpg', alt: 'Campingpark' },
          ],
          amenities: [
            { icon: 'checkin', label: 'Check-in 24/7', tooltip: 'Selbstbedienung Check-in' },
            { icon: 'electric', label: 'Strom' },
            { icon: 'shower', label: 'Dusche' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'water', label: 'Frischwasser' },
            { icon: 'dump', label: 'Abwasserentsorgung' },
            { icon: 'chemical', label: 'Chemie-WC' },
            { icon: 'kitchen', label: 'Küche' },
            { icon: 'washer', label: 'Waschmaschine' },
            { icon: 'trash', label: 'Müllentsorgung' },
            { icon: 'pets', label: 'Haustiere erlaubt' },
          ],
          rows: [
            { item: 'Wohnwagen ohne Strom', price: '20 € / Nacht', note: 'inkl. 2 Personen' },
            { item: 'Wohnwagen mit Strom', price: '25 € / Nacht', note: 'inkl. 2 Personen' },
            { item: 'Wohnwagen Zusatzperson', price: '3 € / Person' },
            { item: 'Zelten', price: '7 € / Person' },
          ],
          badges: {
            checkin: {
              title: 'Automatischer Zugang 24/7',
              body: 'Anreise jederzeit — die Schranke öffnet sich mit dem Buchungscode. Buchen, bezahlen und selbstständig einchecken über pargihaldur.ee.',
              linkLabel: 'Buchen · pargihaldur.ee',
              linkUrl: 'https://willipu.pargihaldur.ee',
            },
            electric: {
              title: 'Stromanschluss · max. 10 A',
              body: 'Die maximale zulässige Last pro Wohnwagen beträgt 10 A. Heizlüfter und Haartrockner sind nicht gestattet. Alle Elektrogeräte müssen einwandfrei funktionieren und die Isolation der Anschlusskabel muss intakt sein.',
            },
            water: {
              title: 'Frischwasser zum Befüllen der Wohnwagen-Tanks',
              body: 'Hinweis: An einem heißen Sommertag das Wasser mindestens 3 Minuten laufen lassen, damit das im Schlauch stehende Wasser durch frisches ersetzt wird.',
            },
          },
        },
        {
          label: 'Sonstiges',
          icon: '❄️',
          rows: [
            { item: 'Winter-Seetransport', price: 'Preis auf Anfrage' },
          ],
        },
      ],
    },
    contact: {
      kicker: 'Kontakt',
      title: 'Besuchen Sie uns oder nehmen Sie Kontakt auf',
      address: 'Dorf Pusi, Gemeinde Alatskivi, Kreis Tartu',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=58.64483549867105,27.166508285762042',
      locationLabel: 'Standort',
      hoursLabel: 'Öffnungszeiten',
      hours: 'Ganzjährig geöffnet',
      phone: '+372 56 955 758',
      email: 'willipu.willipu@gmail.com',
      cta: 'E-Mail senden',
      legal: {
        companyName: 'OÜ Willipu Turism',
        reg: '10972974',
        vat: 'EE100878462',
        legalAddress: 'Villipu, Pusi küla, 60217 Peipsiääre vald, Tartu maakond',
        bankLabel: 'Bankkonto',
        iban: 'EE402200221023806138',
        bank: 'Swedbank AS',
        swift: 'HABAEE2X',
      },
    },
    footer: {
      tagline: 'Am Peipussee seit 2010.',
      rights: 'Alle Rechte vorbehalten',
    },
  },
  fi: {
    nav: {
      about: 'Meistä',
      amenities: 'Aktiviteetit',
      pricing: 'Hinnat',
      contact: 'Yhteystiedot',
    },
    hero: {
      eyebrow: 'Peipsijärven rannalla',
      title: 'Willipu vierastalo ja asuntovaunupuisto',
      subtitle: 'Rauhallinen paikka veden äärellä — kokoontumisiin, lomailuun ja juhliin. Pusin kylässä, Etelä-Virossa.',
      cta: 'Varaa paikka asuntovaunupuistosta',
      ctaAlt: 'Katso hinnat',
      ctaNote: 'Huoneiden ja mökkien varaukset sähköpostitse.',
    },
    about: {
      kicker: 'Tervetuloa',
      title: 'Yli 20 vuoden kokemus',
      body: 'Willipu sijaitsee Tarton maakunnassa, Alatskivin kunnassa, Pusin kylässä – suoraan Peipsijärven rannalla. Lähin kaupunki Kallaste on 2 km päässä, Tartu 50 km ja Tallinn 200 km. Tarjoamme huoneita päätalossa, kesämökkejä, juhlatilan tapahtumia varten sekä täyden asuntovaunualueen.',
      stats: [
        { value: '41', label: 'asuntovaunupaikkaa' },
        { value: '10', label: 'paikkaa päätalossa' },
        { value: '30', label: 'paikkaa juhlatilassa' },
        { value: '16', label: 'paikkaa mökeissä' },
        { value: 'enintään 5', label: 'lisäpaikkaa' },
        { value: '🏖', label: 'lapsiystävällinen hiekkaranta' },
        { value: '🌿', label: 'suuri nurmialue ulkotapahtumia varten' },
        { value: '2 km', label: 'Kallasteen' },
      ],
    },
    amenities: {
      kicker: 'Aktiviteetit',
      title: 'Tekemistä järven rannalla',
      items: [
        { icon: 'wave', title: 'Uinti ja surffaus', body: 'Hiekkaranta, sopii myös purjelautailijoille.' },
        { icon: 'ball', title: 'Lentopallo ja pelit', body: 'Ulkokentät ja avoimet nurmikenttät.' },
        { icon: 'fire', title: 'Nuotio ja sauna', body: 'Nuotiopaikka ja sauna ryhmille.' },
        { icon: 'hall', title: 'Juhlatila 30 hengelle', body: 'Kokoukset, juhlat, koulutukset.' },
        { icon: 'wifi', title: 'Nopea WiFi koko alueella', body: 'Maksuton yhteys sisällä ja ulkoalueella.' },
      ],
    },
    pricing: {
      kicker: 'Hinnat',
      title: 'Edulliset hinnat, kaikki mukavuudet mukana',
      note: '50 %:n ennakkomaksu vahvistaa varauksen. Peruutuksista alle 14 päivää ennen saapumista ennakkomaksua ei palauteta.',
      downloadLabel: 'Lataa hinnasto (.xlsx)',
      groups: [
        {
          label: 'Suuri leirintämökki',
          icon: '🏡',
          photos: [
            { url: '/suur_kamp1.jpg', alt: 'Suuri leirintämökki' },
            { url: '/suur_kamp2.jpg', alt: 'Suuri leirintämökki' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Suihku' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Keittiö' },
            { icon: 'grill', label: 'Grilli' },
          ],
          rows: [
            { item: '5 henkilöä', price: '110 € / yö' },
            { item: '4 henkilöä', price: '100 € / yö' },
            { item: '2–3 henkilöä', price: '85 € / yö' },
          ],
        },
        {
          label: 'Pieni leirintämökki',
          icon: '🛖',
          photos: [
            { url: '/v4.jpeg', alt: 'Pieni leirintämökki' },
            { url: '/v1.jpeg', alt: 'Pieni leirintämökki' },
            { url: '/v2.jpeg', alt: 'Pieni leirintämökki' },
            { url: '/v3.jpeg', alt: 'Pieni leirintämökki' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'grill', label: 'Grilli' },
          ],
          rows: [
            { item: '2 henkilöä', price: '55 € / yö' },
            { item: '1 henkilö', price: '35 € / yö' },
          ],
        },
        {
          label: 'Päätalo - kahden hengen huone',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Päätalo' },
            { url: '/peamaja%201.jpg', alt: 'Päätalo' },
            { url: '/peamaja%202.jpg', alt: 'Päätalo' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Keittiö' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Keittiö' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Suihku' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Yhteiskeittiö' },
            { icon: 'grill', label: 'Grilli' },
          ],
          rows: [
            { item: '2 henkilöä', price: '55 € / yö' },
            { item: '1 henkilö', price: '35 € / yö' },
          ],
        },
        {
          label: 'Päätalo - kolmen hengen huone',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Päätalo' },
            { url: '/peamaja%201.jpg', alt: 'Päätalo' },
            { url: '/peamaja%202.jpg', alt: 'Päätalo' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Keittiö' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Keittiö' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Suihku' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Yhteiskeittiö' },
            { icon: 'grill', label: 'Grilli' },
          ],
          rows: [
            { item: '3 henkilöä', price: '80 € / yö' },
            { item: '2 henkilöä', price: '60 € / yö' },
          ],
        },
        {
          label: 'Asuntovaunupuisto 24/7',
          icon: '🚐',
          photos: [
            { url: '/kar1.jpg', alt: 'Asuntovaunupuisto' },
            { url: '/kar2.jpg', alt: 'Asuntovaunupuisto' },
            { url: '/kar3.jpg', alt: 'Asuntovaunupuisto' },
            { url: '/kar4.jpg', alt: 'Asuntovaunupuisto' },
          ],
          amenities: [
            { icon: 'checkin', label: 'Check-in 24/7', tooltip: 'Itsepalvelu check-in' },
            { icon: 'electric', label: 'Sähkö' },
            { icon: 'shower', label: 'Suihku' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'water', label: 'Puhdas vesi' },
            { icon: 'dump', label: 'Jäteveden tyhjennys' },
            { icon: 'chemical', label: 'Kemiallinen WC' },
            { icon: 'kitchen', label: 'Keittiö' },
            { icon: 'washer', label: 'Pesukone' },
            { icon: 'trash', label: 'Jätteiden käsittely' },
            { icon: 'pets', label: 'Lemmikit sallittu' },
          ],
          rows: [
            { item: 'Asuntovaunu ilman sähköä', price: '20 € / yö', note: 'sis. 2 henkilöä' },
            { item: 'Asuntovaunu sähköllä', price: '25 € / yö', note: 'sis. 2 henkilöä' },
            { item: 'Asuntovaunu lisähenkilö', price: '3 € / henkilö' },
            { item: 'Telttailu', price: '7 € / henkilö' },
          ],
          badges: {
            checkin: {
              title: 'Automaattinen sisäänpääsy 24/7',
              body: 'Saapua voi milloin tahansa — puomi avautuu varauksen koodilla. Varaa, maksa ja tee check-in itsenäisesti pargihaldur.ee-palvelussa.',
              linkLabel: 'Varaa · pargihaldur.ee',
              linkUrl: 'https://willipu.pargihaldur.ee',
            },
            electric: {
              title: 'Sähköliitäntä · max. 10 A',
              body: 'Suurin sallittu teho asuntovaunua kohti on 10 A. Lämpöpuhaltimien ja hiustenkuivaajien käyttö ei ole sallittua. Kaikkien sähkölaitteiden tulee olla kunnossa ja liitäntäkaapeleiden eristyksen ehjiä.',
            },
            water: {
              title: 'Puhdas vesi asuntovaunun vesisäiliön täyttöön',
              body: 'Muistutus: Kuumana kesäpäivänä anna veden juosta vähintään 3 minuuttia, jotta letkussa seisova vesi korvautuu tuoreella.',
            },
          },
        },
        {
          label: 'Muut',
          icon: '❄️',
          rows: [
            { item: 'Talvinen järvikuljetus', price: 'kysy hinta' },
          ],
        },
      ],
    },
    contact: {
      kicker: 'Yhteystiedot',
      title: 'Tule vierailulle tai ota yhteyttä',
      address: 'Pusin kylä, Alatskivin kunta, Tarton maakunta',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=58.64483549867105,27.166508285762042',
      locationLabel: 'Sijainti',
      hoursLabel: 'Aukioloajat',
      hours: 'Auki ympäri vuoden',
      phone: '+372 56 955 758',
      email: 'willipu.willipu@gmail.com',
      cta: 'Lähetä sähköposti',
      legal: {
        companyName: 'OÜ Willipu Turism',
        reg: '10972974',
        vat: 'EE100878462',
        legalAddress: 'Villipu, Pusi küla, 60217 Peipsiääre vald, Tartu maakond',
        bankLabel: 'Pankkitili',
        iban: 'EE402200221023806138',
        bank: 'Swedbank AS',
        swift: 'HABAEE2X',
      },
    },
    footer: {
      tagline: 'Peipsijärven rannalla vuodesta 2010.',
      rights: 'Kaikki oikeudet pidätetään',
    },
  },
  lv: {
    nav: {
      about: 'Par mums',
      amenities: 'Aktivitātes',
      pricing: 'Cenas',
      contact: 'Kontakti',
    },
    hero: {
      eyebrow: 'Pie Peipusa ezera krasta',
      title: 'Willipu viesu nams un kempings',
      subtitle: 'Mierīga vieta pie ūdens — tikšanās, atpūtai un svinībām. Pusi ciemā, dienvidaustrumu Igaunijā.',
      cta: 'Rezervēt vietu kempingā',
      ctaAlt: 'Skatīt cenas',
      ctaNote: 'Istabu un namiņu rezervācijas pa e-pastu.',
    },
    about: {
      kicker: 'Laipni lūdzam',
      title: 'Vairāk nekā 20 gadu pieredze',
      body: 'Willipu atrodas Tartu novadā, Alatskivi pagastā, Pusi ciemā — tieši pie Peipusa ezera krasta. Tuvākā pilsēta Kallaste ir 2 km attālumā, Tartu — 50 km un Tallina — 200 km. Mēs piedāvājam istabas galvenajā mājā, vasarnamiņus, banketu zāli pasākumiem un pilnvērtīgu kempingu.',
      stats: [
        { value: '41', label: 'kempinga vietas' },
        { value: '10', label: 'vietas galvenajā mājā' },
        { value: '30', label: 'vietas banketu zālē' },
        { value: '16', label: 'gultas namiņos' },
        { value: 'līdz 5', label: 'papildu gultas' },
        { value: '🏖', label: 'bērniem draudzīgs smilšu pludmale' },
        { value: '🌿', label: 'liels zālājs āra pasākumiem' },
        { value: '2 km', label: 'līdz Kallastei' },
      ],
    },
    amenities: {
      kicker: 'Aktivitātes',
      title: 'Atpūtas iespējas pie ezera',
      items: [
        { icon: 'wave', title: 'Peldēšana un sērfošana', body: 'Smilšu pludmale, piemērota arī sērfotājiem.' },
        { icon: 'ball', title: 'Volejbols un spēles', body: 'Āra laukumi un brīvas zaļas zonas.' },
        { icon: 'fire', title: 'Ugunskurs un pirts', body: 'Ugunskura vieta un pirts grupām.' },
        { icon: 'hall', title: 'Banketu zāle 30 cilvēkiem', body: 'Konferences, svētki, apmācības.' },
        { icon: 'wifi', title: 'Ātrs WiFi visā teritorijā', body: 'Bezmaksas savienojums telpās un āra zonā.' },
      ],
    },
    pricing: {
      kicker: 'Cenas',
      title: 'Pieejamas cenas ar visām ērtībām',
      note: '50% avansa maksājums apstiprina rezervāciju. Atcelšanas gadījumā mazāk nekā 14 dienas pirms ierašanās avansa maksa netiek atgriezta.',
      downloadLabel: 'Lejupielādēt cenrādi (.xlsx)',
      groups: [
        {
          label: 'Lielais kempinga namiņš',
          icon: '🏡',
          photos: [
            { url: '/suur_kamp1.jpg', alt: 'Lielais kempinga namiņš' },
            { url: '/suur_kamp2.jpg', alt: 'Lielais kempinga namiņš' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Duša' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Virtuve' },
            { icon: 'grill', label: 'Grils' },
          ],
          rows: [
            { item: '5 cilvēkiem', price: '110 € / naktī' },
            { item: '4 cilvēkiem', price: '100 € / naktī' },
            { item: '2–3 cilvēkiem', price: '85 € / naktī' },
          ],
        },
        {
          label: 'Mazais kempinga namiņš',
          icon: '🛖',
          photos: [
            { url: '/v4.jpeg', alt: 'Mazais kempinga namiņš' },
            { url: '/v1.jpeg', alt: 'Mazais kempinga namiņš' },
            { url: '/v2.jpeg', alt: 'Mazais kempinga namiņš' },
            { url: '/v3.jpeg', alt: 'Mazais kempinga namiņš' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'grill', label: 'Grils' },
          ],
          rows: [
            { item: '2 cilvēkiem', price: '55 € / naktī' },
            { item: '1 cilvēkam', price: '35 € / naktī' },
          ],
        },
        {
          label: 'Galvenā māja - divvietīgs numurs',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Galvenā māja' },
            { url: '/peamaja%201.jpg', alt: 'Galvenā māja' },
            { url: '/peamaja%202.jpg', alt: 'Galvenā māja' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Virtuve' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Virtuve' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Duša' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Kopīgā virtuve' },
            { icon: 'grill', label: 'Grils' },
          ],
          rows: [
            { item: '2 cilvēkiem', price: '55 € / naktī' },
            { item: '1 cilvēkam', price: '35 € / naktī' },
          ],
        },
        {
          label: 'Galvenā māja - trīsvietīgs numurs',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Galvenā māja' },
            { url: '/peamaja%201.jpg', alt: 'Galvenā māja' },
            { url: '/peamaja%202.jpg', alt: 'Galvenā māja' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Virtuve' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Virtuve' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Duša' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Kopīgā virtuve' },
            { icon: 'grill', label: 'Grils' },
          ],
          rows: [
            { item: '3 cilvēkiem', price: '80 € / naktī' },
            { item: '2 cilvēkiem', price: '60 € / naktī' },
          ],
        },
        {
          label: 'Kempings 24/7',
          icon: '🚐',
          photos: [
            { url: '/kar1.jpg', alt: 'Kempings' },
            { url: '/kar2.jpg', alt: 'Kempings' },
            { url: '/kar3.jpg', alt: 'Kempings' },
            { url: '/kar4.jpg', alt: 'Kempings' },
          ],
          amenities: [
            { icon: 'checkin', label: 'Check-in 24/7', tooltip: 'Pašapkalpošanās reģistrācija' },
            { icon: 'electric', label: 'Elektrība' },
            { icon: 'shower', label: 'Duša' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'water', label: 'Tīrs ūdens' },
            { icon: 'dump', label: 'Notekūdeņu iztukšošana' },
            { icon: 'chemical', label: 'Ķīmiskais WC' },
            { icon: 'kitchen', label: 'Virtuve' },
            { icon: 'washer', label: 'Veļasmašīna' },
            { icon: 'trash', label: 'Atkritumu nodošana' },
            { icon: 'pets', label: 'Mājdzīvnieki atļauti' },
          ],
          rows: [
            { item: 'Kemperis bez elektrības', price: '20 € / naktī', note: 'ietver 2 cilvēkus' },
            { item: 'Kemperis ar elektrību', price: '25 € / naktī', note: 'ietver 2 cilvēkus' },
            { item: 'Kemperis papildu persona', price: '3 € / persona' },
            { item: 'Telšošana', price: '7 € / persona' },
          ],
          badges: {
            checkin: {
              title: 'Automātiska piekļuve 24/7',
              body: 'Ierasties var jebkurā laikā — barjera atveras ar rezervācijas kodu. Rezervējiet, apmaksājiet un reģistrējieties patstāvīgi vietnē pargihaldur.ee.',
              linkLabel: 'Rezervēt · pargihaldur.ee',
              linkUrl: 'https://willipu.pargihaldur.ee',
            },
            electric: {
              title: 'Elektropievienojums · līdz 10 A',
              body: 'Maksimālā atļautā slodze vienam kempingam ir 10 A. Elektrisko sildītāju un matu žāvētāju izmantošana nav atļauta. Visām elektroierīcēm jābūt labā kārtībā un savienojuma kabeļu izolācijai — neskariai.',
            },
            water: {
              title: 'Tīrs ūdens kempinga ūdens tvertnes uzpildīšanai',
              body: 'Atgādinājums: Karstā vasaras dienā ļauj ūdenim tecēt vismaz 3 minūtes, lai šļūtenē stāvošais ūdens nomainītos ar svaigu.',
            },
          },
        },
        {
          label: 'Citi',
          icon: '❄️',
          rows: [
            { item: 'Ziemas transportēšana pa ezeru', price: 'jautājiet cenu' },
          ],
        },
      ],
    },
    contact: {
      kicker: 'Kontakti',
      title: 'Apmeklējiet mūs vai sazinieties',
      address: 'Pusi ciems, Alatskivi pagasts, Tartu novads',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=58.64483549867105,27.166508285762042',
      locationLabel: 'Atrašanās vieta',
      hoursLabel: 'Darba laiks',
      hours: 'Atvērts visu gadu',
      phone: '+372 56 955 758',
      email: 'willipu.willipu@gmail.com',
      cta: 'Sūtīt e-pastu',
      legal: {
        companyName: 'OÜ Willipu Turism',
        reg: '10972974',
        vat: 'EE100878462',
        legalAddress: 'Villipu, Pusi küla, 60217 Peipsiääre vald, Tartu maakond',
        bankLabel: 'Bankas konts',
        iban: 'EE402200221023806138',
        bank: 'Swedbank AS',
        swift: 'HABAEE2X',
      },
    },
    footer: {
      tagline: 'Pie Peipusa ezera kopš 2010. gada.',
      rights: 'Visas tiesības aizsargātas',
    },
  },
  lt: {
    nav: {
      about: 'Apie mus',
      amenities: 'Veikla',
      pricing: 'Kainos',
      contact: 'Kontaktai',
    },
    hero: {
      eyebrow: 'Prie Peipaus ežero kranto',
      title: 'Willipu svečių namai ir kempingas',
      subtitle: 'Rami vieta prie vandens — susitikimams, poilsiui ir šventėms. Pusi kaime, pietų Estijoje.',
      cta: 'Rezervuoti vietą kempinge',
      ctaAlt: 'Žiūrėti kainas',
      ctaNote: 'Kambarių ir namelio rezervacijos el. paštu.',
    },
    about: {
      kicker: 'Sveiki atvykę',
      title: 'Daugiau nei 20 metų patirtis',
      body: 'Willipu yra Tartu apskrityje, Alatskivi seniūnijoje, Pusi kaime — tiesiai prie Peipaus ežero kranto. Artimiausias miestas Kallaste yra 2 km, Tartu — 50 km, Talinas — 200 km. Siūlome kambarius pagrindiniame name, vasarnamiukus, salę renginiams ir pilnavertį kempingą.',
      stats: [
        { value: '41', label: 'kempingo vietos' },
        { value: '10', label: 'vietų pagrindiniame name' },
        { value: '30', label: 'vietų banketų salėje' },
        { value: '16', label: 'lovos nameliuose' },
        { value: 'iki 5', label: 'papildomos lovos' },
        { value: '🏖', label: 'vaikams draugiška smėlio paplūdimys' },
        { value: '🌿', label: 'didelis vejos plotas lauko renginiams' },
        { value: '2 km', label: 'iki Kallaste' },
      ],
    },
    amenities: {
      kicker: 'Veikla',
      title: 'Pramogos prie ežero',
      items: [
        { icon: 'wave', title: 'Plaukimas ir banglentė', body: 'Smėlio paplūdimys, tinkamas ir banglenčiams.' },
        { icon: 'ball', title: 'Tinklinis ir žaidimai', body: 'Lauko aikštelės ir atviros žolės erdvės.' },
        { icon: 'fire', title: 'Laužas ir pirtis', body: 'Laužavietė ir pirtis grupėms.' },
        { icon: 'hall', title: 'Salė 30 žmonių', body: 'Konferencijos, šventės, mokymai.' },
        { icon: 'wifi', title: 'Greitas WiFi visoje teritorijoje', body: 'Nemokamas ryšys patalpose ir lauke.' },
      ],
    },
    pricing: {
      kicker: 'Kainos',
      title: 'Prieinamos kainos su visais patogumais',
      note: '50% išankstinis mokėjimas patvirtina rezervaciją. Atšaukus rezervaciją likus mažiau nei 14 dienų iki atvykimo, avansas negrąžinamas.',
      downloadLabel: 'Atsisiųsti kainoraštį (.xlsx)',
      groups: [
        {
          label: 'Didelis kempingo namelis',
          icon: '🏡',
          photos: [
            { url: '/suur_kamp1.jpg', alt: 'Didelis kempingo namelis' },
            { url: '/suur_kamp2.jpg', alt: 'Didelis kempingo namelis' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Dušas' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Virtuvė' },
            { icon: 'grill', label: 'Grilis' },
          ],
          rows: [
            { item: '5 asmenims', price: '110 € / naktis' },
            { item: '4 asmenims', price: '100 € / naktis' },
            { item: '2–3 asmenims', price: '85 € / naktis' },
          ],
        },
        {
          label: 'Mažas kempingo namelis',
          icon: '🛖',
          photos: [
            { url: '/v4.jpeg', alt: 'Mažas kempingo namelis' },
            { url: '/v1.jpeg', alt: 'Mažas kempingo namelis' },
            { url: '/v2.jpeg', alt: 'Mažas kempingo namelis' },
            { url: '/v3.jpeg', alt: 'Mažas kempingo namelis' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'grill', label: 'Grilis' },
          ],
          rows: [
            { item: '2 asmenims', price: '55 € / naktis' },
            { item: '1 asmeniui', price: '35 € / naktis' },
          ],
        },
        {
          label: 'Pagrindinis namas - dvivietis kambarys',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Pagrindinis namas' },
            { url: '/peamaja%201.jpg', alt: 'Pagrindinis namas' },
            { url: '/peamaja%202.jpg', alt: 'Pagrindinis namas' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Virtuvė' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Virtuvė' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Dušas' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Bendra virtuvė' },
            { icon: 'grill', label: 'Grilis' },
          ],
          rows: [
            { item: '2 asmenims', price: '55 € / naktis' },
            { item: '1 asmeniui', price: '35 € / naktis' },
          ],
        },
        {
          label: 'Pagrindinis namas - trivietis kambarys',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Pagrindinis namas' },
            { url: '/peamaja%201.jpg', alt: 'Pagrindinis namas' },
            { url: '/peamaja%202.jpg', alt: 'Pagrindinis namas' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Virtuvė' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Virtuvė' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Dušas' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Bendra virtuvė' },
            { icon: 'grill', label: 'Grilis' },
          ],
          rows: [
            { item: '3 asmenims', price: '80 € / naktis' },
            { item: '2 asmenims', price: '60 € / naktis' },
          ],
        },
        {
          label: 'Kempingas 24/7',
          icon: '🚐',
          photos: [
            { url: '/kar1.jpg', alt: 'Kempingas' },
            { url: '/kar2.jpg', alt: 'Kempingas' },
            { url: '/kar3.jpg', alt: 'Kempingas' },
            { url: '/kar4.jpg', alt: 'Kempingas' },
          ],
          amenities: [
            { icon: 'checkin', label: 'Check-in 24/7', tooltip: 'Savitarnos registracija' },
            { icon: 'electric', label: 'Elektra' },
            { icon: 'shower', label: 'Dušas' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'water', label: 'Gėlas vanduo' },
            { icon: 'dump', label: 'Nuotekų išleidimas' },
            { icon: 'chemical', label: 'Cheminis WC' },
            { icon: 'kitchen', label: 'Virtuvė' },
            { icon: 'washer', label: 'Skalbimo mašina' },
            { icon: 'trash', label: 'Atliekų tvarkymas' },
            { icon: 'pets', label: 'Augintiniai leidžiami' },
          ],
          rows: [
            { item: 'Kemperis be elektros', price: '20 € / naktis', note: 'apima 2 asmenis' },
            { item: 'Kemperis su elektra', price: '25 € / naktis', note: 'apima 2 asmenis' },
            { item: 'Kemperio papildomas asmuo', price: '3 € / asmuo' },
            { item: 'Palapinė', price: '7 € / asmuo' },
          ],
          badges: {
            checkin: {
              title: 'Automatinis patekimas 24/7',
              body: 'Atvykti galima bet kada — vartai atsidarys su rezervacijos kodu. Rezervuokite, apmokėkite ir registruokitės savarankiškai per pargihaldur.ee.',
              linkLabel: 'Rezervuoti · pargihaldur.ee',
              linkUrl: 'https://willipu.pargihaldur.ee',
            },
            electric: {
              title: 'Elektros jungtis · iki 10 A',
              body: 'Didžiausia leistina apkrova vienam kempingui yra 10 A. Šildytuvų ir plaukų džiovintuvų naudojimas neleidžiamas. Visi elektros prietaisai turi būti tvarkingi, o jungimo kabelių izoliacija — nepažeista.',
            },
            water: {
              title: 'Švarus vanduo kemperio vandens bakui pildyti',
              body: 'Priminti: Karštą vasaros dieną leiskite vandeniui tekėti bent 3 minutes, kad žarnoje stovėjęs vanduo pakeistų šviežiu.',
            },
          },
        },
        {
          label: 'Kita',
          icon: '❄️',
          rows: [
            { item: 'Žiemos transportavimas per ežerą', price: 'teiraukitės kainos' },
          ],
        },
      ],
    },
    contact: {
      kicker: 'Kontaktai',
      title: 'Apsilankykite arba susisiekite',
      address: 'Pusi kaimas, Alatskivi seniūnija, Tartu apskritis',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=58.64483549867105,27.166508285762042',
      locationLabel: 'Vieta',
      hoursLabel: 'Darbo laikas',
      hours: 'Atidaryta ištisus metus',
      phone: '+372 56 955 758',
      email: 'willipu.willipu@gmail.com',
      cta: 'Siųsti el. laišką',
      legal: {
        companyName: 'OÜ Willipu Turism',
        reg: '10972974',
        vat: 'EE100878462',
        legalAddress: 'Villipu, Pusi küla, 60217 Peipsiääre vald, Tartu maakond',
        bankLabel: 'Banko sąskaita',
        iban: 'EE402200221023806138',
        bank: 'Swedbank AS',
        swift: 'HABAEE2X',
      },
    },
    footer: {
      tagline: 'Prie Peipaus ežero nuo 2010 m.',
      rights: 'Visos teisės saugomos',
    },
  },
  ru: {
    nav: {
      about: 'О нас',
      amenities: 'Активности',
      pricing: 'Цены',
      contact: 'Контакты',
    },
    hero: {
      eyebrow: 'На берегу Чудского озера',
      title: 'Гостевой дом и кемпинг Willipu',
      subtitle: 'Тихое место у воды — для встреч, отдыха и праздников. Тартумаа, деревня Пуси.',
      cta: 'Забронировать кемпинг',
      ctaAlt: 'Посмотреть цены',
      ctaNote: 'Бронирование номеров и коттеджей по электронной почте.',
    },
    about: {
      kicker: 'Добро пожаловать',
      title: 'Более 20 лет опыта',
      body: 'Willipu расположен в Тартумаа, волости Алатскиви, деревне Пуси, прямо на берегу Чудского озера. Ближайший город Каллясте находится в 2 км, Тарту — в 50 км, Таллин — в 200 км. Мы предлагаем номера в главном доме, летние коттеджи, банкетный зал для мероприятий и кемпинг для домов на колёсах.',
      stats: [
        { value: '41', label: 'мест для кемпинга' },
        { value: '10', label: 'мест в главном доме' },
        { value: '30', label: 'мест в банкетном зале' },
        { value: '16', label: 'мест в коттеджах' },
        { value: 'до 5', label: 'дополнительных мест' },
        { value: '🏖', label: 'песчаный пляж для детей' },
        { value: '🌿', label: 'большой газон для мероприятий' },
        { value: '2 км', label: 'до Калласте' },
      ],
    },
    amenities: {
      kicker: 'Чем заняться',
      title: 'Активности у воды',
      items: [
        { icon: 'wave', title: 'Купание и сёрфинг', body: 'Песчаный пляж, подходит и для сёрфинга.' },
        { icon: 'ball', title: 'Волейбол и игры', body: 'Спортплощадки и открытые травяные поля.' },
        { icon: 'fire', title: 'Костёр и сауна', body: 'Место для костра и сауна для компании.' },
        { icon: 'hall', title: 'Банкетный зал до 30 чел.', body: 'Конференции, вечеринки, тренинги.' },
        { icon: 'wifi', title: 'Быстрый WiFi по всей территории', body: 'Бесплатный доступ в помещениях и на открытом воздухе.' },
      ],
    },
    pricing: {
      kicker: 'Цены',
      title: 'Доступные цены со всеми удобствами',
      note: 'Для подтверждения бронирования вносится предоплата 50%. При отмене менее чем за 14 дней предоплата не возвращается.',
      downloadLabel: 'Скачать прайс-лист (.xlsx)',
      groups: [
        {
          label: 'Большой коттедж',
          icon: '🏡',
          photos: [
            { url: '/suur_kamp1.jpg', alt: 'Большой коттедж' },
            { url: '/suur_kamp2.jpg', alt: 'Большой коттедж' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Душ' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Кухня' },
            { icon: 'grill', label: 'Гриль' },
          ],
          rows: [
            { item: '5 человек', price: '110 € / ночь' },
            { item: '4 человека', price: '100 € / ночь' },
            { item: '2–3 человека', price: '85 € / ночь' },
          ],
        },
        {
          label: 'Малый коттедж',
          icon: '🛖',
          photos: [
            { url: '/v4.jpeg', alt: 'Малый коттедж' },
            { url: '/v1.jpeg', alt: 'Малый коттедж' },
            { url: '/v2.jpeg', alt: 'Малый коттедж' },
            { url: '/v3.jpeg', alt: 'Малый коттедж' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'grill', label: 'Гриль' },
          ],
          rows: [
            { item: '2 человека', price: '55 € / ночь' },
            { item: '1 человек', price: '35 € / ночь' },
          ],
        },
        {
          label: 'Главный дом - двухместный номер',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Главный дом' },
            { url: '/peamaja%201.jpg', alt: 'Главный дом' },
            { url: '/peamaja%202.jpg', alt: 'Главный дом' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Кухня' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Кухня' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Душ' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Общая кухня' },
            { icon: 'grill', label: 'Гриль' },
          ],
          rows: [
            { item: '2 человека', price: '55 € / ночь' },
            { item: '1 человек', price: '35 € / ночь' },
          ],
        },
        {
          label: 'Главный дом - трёхместный номер',
          icon: '🛏',
          photos: [
            { url: '/peamaja.jpg', alt: 'Главный дом' },
            { url: '/peamaja%201.jpg', alt: 'Главный дом' },
            { url: '/peamaja%202.jpg', alt: 'Главный дом' },
            { url: '/K%C3%B6%C3%B6k_1.jpg', alt: 'Кухня' },
            { url: '/k%C3%B6%C3%B6k_2.jpg', alt: 'Кухня' },
          ],
          amenities: [
            { icon: 'wc', label: 'WC' },
            { icon: 'shower', label: 'Душ' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'kitchen', label: 'Общая кухня' },
            { icon: 'grill', label: 'Гриль' },
          ],
          rows: [
            { item: '3 человека', price: '80 € / ночь' },
            { item: '2 человека', price: '60 € / ночь' },
          ],
        },
        {
          label: 'Кемпинг 24/7',
          icon: '🚐',
          photos: [
            { url: '/kar1.jpg', alt: 'Кемпинг' },
            { url: '/kar2.jpg', alt: 'Кемпинг' },
            { url: '/kar3.jpg', alt: 'Кемпинг' },
            { url: '/kar4.jpg', alt: 'Кемпинг' },
          ],
          amenities: [
            { icon: 'checkin', label: 'Заезд 24/7', tooltip: 'Самостоятельный заезд' },
            { icon: 'electric', label: 'Электричество' },
            { icon: 'shower', label: 'Душ' },
            { icon: 'wifi', label: 'WiFi' },
            { icon: 'water', label: 'Чистая вода' },
            { icon: 'dump', label: 'Слив отходов' },
            { icon: 'chemical', label: 'Хим. туалет' },
            { icon: 'kitchen', label: 'Кухня' },
            { icon: 'washer', label: 'Стиральная машина' },
            { icon: 'trash', label: 'Вывоз мусора' },
            { icon: 'pets', label: 'Питомцы разрешены' },
          ],
          rows: [
            { item: 'Дом на колёсах без электричества', price: '20 € / ночь', note: 'включено 2 чел.' },
            { item: 'Дом на колёсах с электричеством', price: '25 € / ночь', note: 'включено 2 чел.' },
            { item: 'Доп. человек для дома на колёсах', price: '3 € / чел.' },
            { item: 'Палатка', price: '7 € / чел.' },
          ],
          badges: {
            checkin: {
              title: 'Автоматический доступ 24/7',
              body: 'Приезжайте в любое время — шлагбаум откроется с кодом из бронирования. Бронируйте, оплачивайте и регистрируйтесь самостоятельно на pargihaldur.ee.',
              linkLabel: 'Забронировать · pargihaldur.ee',
              linkUrl: 'https://willipu.pargihaldur.ee',
            },
            electric: {
              title: 'Электроподключение · до 10 А',
              body: 'Максимально допустимая нагрузка на один дом на колёсах — 10 А. Использование тепловентиляторов и фенов не разрешено. Все электроприборы должны быть исправны, изоляция соединительных кабелей — без повреждений.',
            },
            water: {
              title: 'Чистая вода для наполнения баков домов на колёсах',
              body: 'Напоминание: В жаркий летний день пропустите воду не менее 3 минут, чтобы вода, застоявшаяся в шланге, сменилась свежей.',
            },
          },
        },
        {
          label: 'Прочее',
          icon: '❄️',
          rows: [
            { item: 'Зимний транспорт по озеру', price: 'уточнить цену' },
          ],
        },
      ],
    },
    contact: {
      kicker: 'Контакты',
      title: 'Приезжайте или свяжитесь с нами',
      address: 'Деревня Пуси, волость Алатскиви, Тартумаа',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=58.64483549867105,27.166508285762042',
      locationLabel: 'Адрес',
      hoursLabel: 'Часы работы',
      hours: 'Открыто круглый год',
      phone: '+372 56 955 758',
      email: 'willipu.willipu@gmail.com',
      cta: 'Написать письмо',
      legal: {
        companyName: 'OÜ Willipu Turism',
        reg: '10972974',
        vat: 'EE100878462',
        legalAddress: 'Villipu, Pusi küla, 60217 Peipsiääre vald, Tartu maakond',
        bankLabel: 'Банковский счёт',
        iban: 'EE402200221023806138',
        bank: 'Swedbank AS',
        swift: 'HABAEE2X',
      },
    },
    footer: {
      tagline: 'На берегу Чудского озера с 2010 года.',
      rights: 'Все права защищены',
    },
  },
}

export const gallery = [
  {
    url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&q=80',
    alt: 'Lake at sunrise',
  },
  {
    url: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=1200&q=80',
    alt: 'Wooden cottage in trees',
  },
  {
    url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80',
    alt: 'Misty forest morning',
  },
  {
    url: 'https://images.unsplash.com/photo-1499696010180-025ef6e1a8f9?w=1200&q=80',
    alt: 'Cabin interior with wood',
  },
  {
    url: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=1200&q=80',
    alt: 'Pine forest by water',
  },
  {
    url: 'https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=1200&q=80',
    alt: 'Boat dock at golden hour',
  },
]

export const heroImage = '/52c0d4c0-7aea-429a-b0f0-0f4a1ca2155d.jpg'
